"""Gradio demo UI — one chat, artifact-style report panel.

A single multimodal input drives everything: attach a lease (or click the
sample-lease example) to scan it; just type to ask questions. Scan progress
streams into the chat clause by clause; the finished report pins to the
right-hand panel so it stays visible while you chat about it. The chat's
context is explicit — Washington law always, plus the latest scan report once
a scan has run.

Privacy: uploads are parsed in memory and the temp file is deleted right after
parsing; clause text goes to the OpenAI API for analysis and is never written
to disk. Finished scans are cached in process memory, keyed by document
content hash, so rescanning an identical document costs zero API calls.

Usage:
    python -m leasehound.app     # http://localhost:7860
"""

import hashlib
import os
import re
import shutil
import tempfile
import threading
import time
import traceback
from collections import OrderedDict
from html import escape
from pathlib import Path

import gradio as gr
from starlette.responses import Response

from leasehound.answer import (
    MAX_HISTORY_MESSAGE_CHARS,
    QuestionTooLong,
    answer_question,
)
from leasehound.jurisdiction import jurisdiction_mismatch
from leasehound.metrics import UsageMeter, log_scan
from leasehound.report_html import render_report_html
from leasehound.scan import (
    MAX_CLAUSES,
    DocumentTooLarge,
    EncryptedDocument,
    NoTextExtracted,
    ScanResult,
    count_verdicts,
    render_report,
    scan_steps,
    summary_counts,
)
from leasehound.upload import MAX_UPLOAD_BYTES, read_document

REPO_ROOT = Path(__file__).parent.parent
SAMPLE_LEASE = REPO_ROOT / "examples" / "sample_lease.md"
# The hosted demo serves one jurisdiction. Named once: the scan and the report used
# to be handed the string "wa" separately, and the scan path took it as a default
# argument while this file hard-coded it, so they could disagree silently.
DEMO_STATE = "wa"
ICONS = Path(__file__).parent / "assets"

HERO = """
<div class="hero">
  <div class="wordmark">🐕 LeaseHound</div>
  <p class="tagline">Sniffs out the clauses that shouldn't be there.</p>
</div>
"""

CSS = """
/* The type scale. Seven sizes, one per job, in px — the panel's sizes used to be `em`
   multipliers off an inherited 14px and landed on 12.88, 11.48, 10.64, 10.08, which is
   not a scale, it is wherever the multiplication finished. Two of those were the same
   job at different sizes: the example groups' label (11.04px) and the report's section
   headings (10.64px) both say "this is a label".
   --body and --control are 16 and 14 because that is what Gradio already sets for
   messages and for controls; picking anything else means every control fights the
   framework. The rest are chosen against those two.
   Roles that stay DIFFERENT, on purpose: the conversation reads at --body, the report
   reads one step below at --doc (it is a dense document, not a chat), and the lease's
   own words are the one serif on the page. */
.gradio-container {max-width: 1200px !important; margin: 0 auto !important;
    --t-display: 34px;   /* the wordmark, once per page */
    --t-title: 18px;     /* "Scan report" — the title of a surface, not of the page */
    --t-lead: 17px;      /* the tagline under the wordmark */
    --t-body: 16px;      /* conversation, and anything read as prose */
    --t-control: 14px;   /* composer, example buttons — Gradio's own size */
    --t-quote: 14px;     /* the lease's own words: a serif set at --doc reads smaller
                            than the sans beside it, and this is the one thing on the
                            panel that is quoted rather than written */
    --t-doc: 13px;       /* the report's body text, and the line about what is loaded */
    --t-meta: 12px;      /* verdict chips, file names, statute citations */
    --t-label: 11px;     /* every uppercase label, and the caveat */
}
.hero {text-align: center; padding: 12px 0 8px;}
.hero .wordmark {font-size: var(--t-display); font-weight: 700; letter-spacing: -0.5px;}
.hero .tagline {font-size: var(--t-lead); margin: 6px 0 4px;}
.step-sub {font-size: var(--t-doc); opacity: 0.75;}
/* Same file name, same treatment. Markdown backticks made this one a tinted monospace
   chip while the report's copy of the identical string was plain text. */
.step-sub code {font-family: inherit !important; font-size: inherit !important;
    font-weight: 500; background: none !important; border: 0 !important;
    padding: 0 !important; color: inherit;}
.main-row {justify-content: center; align-items: stretch;}
/* The report panel. Styled to match the share card at docs/og.png, which is
   generated by scripts/make_og.py from the same report — a card that looks more
   finished than the product it links to is a downgrade on arrival.
   Every class here is emitted by report_html.py; nothing depends on Markdown's
   generated structure, which is what the old h1/h2 rules were doing. */
/* Surfaces, from the share card, in the card's own direction: the surface is white and
   the boxes on it are filled a shade darker (#f6f8fa, the card's CHROME; its chips use
   #f8fafc). One hairline, #dbe2ea, the card's EDGE. The app used to be #ffffff boxes on
   a #f8fafc page — three units apart, so nothing had depth and only a border separated
   anything; then briefly the reverse of the card, grey page and white boxes, which had
   depth pointing the wrong way. --lh-card is read by every filled box in the panel, so
   this is one value to change, not eight. */
.report-panel {--lh-red: #dc2626; --lh-amber: #d97706; --lh-teal: #0d9488;
               --lh-green: #16a34a; --lh-ink: #0f172a; --lh-body: #334155;
               --lh-muted: #94a3b8; --lh-hair: #e2e8f0; --lh-card: #f8fafc;}
.report-panel .lh-md {display: none;}
.report-panel .lh-title {font-size: var(--t-title); font-weight: 700; color: var(--lh-ink);
                         margin: 2px 0 3px; display: flex; align-items: baseline; gap: 10px;}
/* The file name rides on the title line: it is what the report is OF, not metadata
   about it. No mono — one typeface in the whole app now, and an identifier can say what
   it is with weight and colour. */
.report-panel .lh-file {font-weight: 500;
                        font-size: var(--t-meta); font-weight: 400; color: var(--lh-muted);}
.report-panel .lh-prov {font-size: var(--t-label); color: var(--lh-muted); margin: 0 0 13px;}
.report-panel .lh-dot {margin: 0 7px;}
/* Verdict counts as chips, the one thing a Markdown string could not carry: the
   summary used to be one bold run with "·" between the numbers, and four emoji
   doing the colour coding — 🚩⚠️🔍✅ is four visual weights and four metaphors in
   a row, rendered differently on every platform. The dot is drawn now. */
.report-panel .lh-chips {display: flex; flex-wrap: wrap; gap: 8px; margin: 0 0 16px;}
.report-panel .lh-chip {display: inline-flex; align-items: center; gap: 8px;
                        font-size: var(--t-meta); font-weight: 600; color: var(--lh-body);
                        padding: 6px 12px; border: 1px solid var(--lh-hair);
                        border-radius: 999px; white-space: nowrap;
                        background: var(--lh-card);}
.report-panel .lh-chip i {width: 9px; height: 9px; border-radius: 2px; flex: none;}
.report-panel .lh-red i {background: var(--lh-red);}
.report-panel .lh-yellow i {background: var(--lh-amber);}
.report-panel .lh-missing i {background: var(--lh-teal);}
.report-panel .lh-green i {background: var(--lh-green);}
.report-panel .lh-note {font-size: var(--t-doc); color: var(--lh-body); line-height: 1.42;
                        /* 8px, the app's one radius — see the theme tokens in
                           UI_STYLE. Was 8, then 10 to match .lh-finding, now 8 again
                           with .lh-finding: the panel agreeing with itself was the
                           small version of the problem. */
                        margin: 0 0 10px; padding: 12px 14px; border-radius: 8px;
                        background: var(--lh-card); border-left: 3px solid var(--lh-hair);}
.report-panel .lh-note-jurisdiction, .report-panel .lh-note-gate,
.report-panel .lh-note-partial {background: #fffbeb; border-left-color: var(--lh-amber);}
.report-panel .lh-section {font-size: var(--t-label); font-weight: 700; letter-spacing: 0.08em;
                           text-transform: uppercase; margin: 18px 0 8px;}
.report-panel h2.lh-red {color: var(--lh-red);}
.report-panel h2.lh-yellow {color: var(--lh-amber);}
.report-panel h2.lh-missing {color: var(--lh-teal);}
/* One finding, one card: hairline border, white fill, nothing else. Findings used to
   run together as heading + paragraph + list, so which explanation belonged to which
   clause was a matter of reading order — that is what the card fixes.
   What the card no longer does is repeat the verdict. It used to carry a 4px coloured
   rail down its left edge and, for red, a pink fill and a pink border: three
   statements of "this one is a red flag" under a section heading that already said so
   in red. The section groups them; the card only has to hold one. */
.report-panel .lh-finding {margin: 0 0 9px; padding: 12px 14px;
                           border: 1px solid var(--lh-hair); border-radius: 8px;
                           background: var(--lh-card);}
.report-panel .lh-finding-head {font-size: var(--t-label); font-weight: 700; letter-spacing: 0.07em;
                                text-transform: uppercase; color: var(--lh-muted);
                                margin: 0 0 6px;}
/* The one place a second typeface earns its keep: this is the lease's own words, and
   the sans beside it is the tool's words about them. Everything else on the panel now
   inherits Gradio's stack, so the panel and the chat column beside it set the same. */
/* !important on the margins, and it is load-bearing: gradio's prose stylesheet gives a
   <blockquote> a 24px top margin and wins on order, so every finding opened with 36px
   of air above its first line (12px of padding plus that) — measured on the page, where
   this rule's own `margin: 0` read back as 24px. Same for the <p> below it. */
/* The lease's own words, in the app's one typeface. This was the last serif; it said
   "someone else wrote this", which weight and colour say too. */
.report-panel .lh-clause {font-weight: 600;
                          font-size: var(--t-quote); line-height: 1.4; color: var(--lh-ink);
                          margin: 0 0 7px !important; padding: 0; border: none;
                          background: none;}
.report-panel .lh-explain {font-size: var(--t-doc); line-height: 1.45; color: var(--lh-body);
                           margin: 0 !important;}
.report-panel .lh-cites {display: flex; flex-wrap: wrap; gap: 8px; margin: 10px 0 0;}
/* No underline anywhere, at rest or on hover. Every clickable thing in this app now says
   so the same way: a mint wash under the pointer. The citation gets it as a rounded
   highlight rather than as a filled button, because it lives inside a sentence — same
   colour, same message, shaped for where it sits. */
.report-panel .lh-cite {font-size: var(--t-meta); font-weight: 500; color: #0f766e;
                        text-decoration: none; border-radius: 4px;
                        padding: 1px 3px; margin: 0 -3px;
                        transition: background-color 0.15s ease;}
.report-panel a.lh-cite:hover {background: #f0fdfa; text-decoration: none;}
.report-panel .lh-missing-list {margin: 0; padding-left: 20px; font-size: var(--t-doc);
                                line-height: 1.6; color: var(--lh-body);}
.report-panel .lh-tail {font-size: var(--t-doc); color: var(--lh-muted); margin: 14px 0 0;}
/* The foot: provenance, then the caveat. Quiet, and last. Present on every report,
   competing with none of it. One rule above the pair rather than one each. */
.report-panel .lh-prov-foot {margin: 18px 0 3px; padding-top: 12px; font-size: var(--t-label);
                             border-top: 1px solid var(--lh-hair);}
.report-panel .lh-legal {font-size: var(--t-label); line-height: 1.4; color: var(--lh-muted);
                         margin: 0 0 2px;}
.report-panel .lh-waiting {font-size: var(--t-doc); color: var(--lh-muted);}
.report-panel .lh-notjudged {color: var(--lh-amber);}
@media (prefers-color-scheme: dark) {
  .report-panel {--lh-ink: #e6edf3; --lh-body: #c3ccd6; --lh-muted: #7d8b99;
                 --lh-hair: #263139;}
  .report-panel .lh-finding {background: #11181f; border-color: #263139;}
  .report-panel .lh-finding.lh-red {background: #1b1315; border-color: #4a2226;}
  .report-panel .lh-note {background: #11181f;}
  .report-panel .lh-note-jurisdiction, .report-panel .lh-note-gate,
  .report-panel .lh-note-partial {background: #1d1710;}
  .report-panel .lh-cite {color: #2dd4bf; border-bottom-color: rgba(45, 212, 191, 0.3);}
}
/* The [copy][download][trash] row pins to the column's top-right corner and
   stays put while the report scrolls underneath. */
.report-col {position: relative;}
#report-actions {position: absolute; top: 6px; right: 6px; z-index: 10;
                 width: auto; min-width: 0; gap: 6px; flex-wrap: nowrap;}
/* Icon-only buttons: gradio gives button imgs max-width:100%, which resolves
   against the empty label's collapsed content box and squashes the icon to 0. */
#report-actions button {width: auto; min-width: 30px; flex-grow: 0; padding: 4px 8px;}
#report-actions button img {width: 13px; height: 13px; margin: 0;
                            max-width: none; flex-shrink: 0;}
/* Desktop layout. Both columns get explicit widths (flex-grow stays 0) so the
   solo ↔ split switch is a deterministic slide: animating flex-grow instead
   makes widths depend on the grow *ratio*, which overshoots — the chat column
   balloons to full row width the instant its sibling leaves the DOM, then
   shrinks back. flex-basis is not !important so the entry keyframe can drive
   it (CSS animations lose to !important declarations). */
@media (min-width: 901px) {
  /* nowrap: gradio Rows wrap, and for the 0.45s the chat column spends animating from
     760px down to 50%, 760 + the report column's content did not fit — so the column
     (carrying "Call off the hound") wrapped BELOW the chat and jumped up to the right
     when the animation finished. Both columns have an explicit basis and min-width: 0,
     so there is nothing here that needs to wrap. Narrow screens stack by
     flex-direction and are unaffected. */
  .main-row {flex-wrap: nowrap !important;}
  .chat-col {transition: flex-basis 0.45s ease;}
  .main-row:not(:has(.report-col)) .chat-col {flex-grow: 0 !important; flex-basis: 760px; max-width: 760px;}
  .main-row:has(.report-col) .chat-col {flex-grow: 0 !important; flex-basis: calc(50% - (var(--layout-gap, 8px) / 2));}
  /* Side-by-side, the report column stretches to the chat column's height and
     the report scrolls inside it, so both columns end flush. */
  .report-col {display: flex !important; flex-direction: column;
               flex-grow: 0 !important;
               flex-basis: calc(50% - (var(--layout-gap, 8px) / 2));
               min-width: 0 !important; overflow: hidden;
               transition: flex-basis 0.45s ease, opacity 0.45s ease;
               animation: report-in 0.45s ease;}
  @keyframes report-in {from {flex-basis: 0px; opacity: 0;}}
  /* overflow-y needs !important and the rest of this rule does not, which is worth
     writing down. As a gr.Markdown the panel took this rule as written. As a gr.HTML
     it also carries Gradio's `hide-contain`, which sets overflow and wins — so `flex`
     and `min-height` still landed while `overflow-y` silently did not, and a long
     report was CLIPPED at the column's height. Nothing looked broken: the panel
     rendered, the wheel scrolled the page past it, and the findings below the fold
     were simply unreachable. Narrow screens use their own rule below and never were.
     Measured rather than guessed — computed overflow-y read `visible` on the live
     page, while flex and min-height read as written. */
  .report-panel {flex: 1 1 0; min-height: 0; overflow-y: auto !important; padding: 0 4px;}
  /* Trash: TRASH_JS adds .closing so both columns slide to their solo
     positions *before* the server removes the report column from the DOM
     (on_trash sleeps past the transition). Must come after the :has rules —
     same specificity, so source order decides. */
  .main-row.closing .chat-col {flex-basis: 760px;}
  .main-row.closing .report-col {flex-basis: 0px; opacity: 0;}
}
@media (max-width: 900px) {
  /* No max-height here, and that is a decision rather than the absence of one. This
     rule used to cap the panel at 65vh and scroll inside it, but `hide-contain` ate
     the overflow declaration the same way it ate the desktop one — so the cap applied
     while the scrolling did not, and the report simply spilled out of its own box.
     A long report would have overlapped whatever followed it.
     Restoring the cap was the other option. It loses: stacked on a phone the chat is
     already above the report rather than beside it, so capping the report buys no
     visible chat and costs a nested scroll box, which is the fiddliest thing to
     operate on a touch screen. The panel takes its full height and the page scrolls,
     which is what it was already doing by accident. */
  .report-panel {padding: 0 4px;}
}
/* STRETCH, not center. This rule said `center` and was written when gradio 5 laid
   the container out as a ROW, where centering the cross axis meant centering the
   icons and the textarea vertically. Gradio 6 makes the container a COLUMN, so the
   same declaration centers the cross axis HORIZONTALLY: the input wrapper collapsed
   to its content and the composer went from 734px wide to 237px, wrapping the
   placeholder onto two lines and clipping "Washington…" off the end. Nothing caught
   it — the tests render no CSS, and the README screenshot that would have shown it
   predated the upgrade. The vertical centering it used to do is now the textarea's
   own align-content, below. */
.chat-col .multimodal-textbox .input-row {align-items: center;}
/* With a file attached the chip sits ABOVE the input, and its glyph was centred in a 40px
   box — so the icon began 10px to the right of the text under it. Left-align the glyph
   and both start on the same edge, with no measurement to go stale. */
.chat-col .multimodal-textbox .thumbnail-item {justify-content: flex-start;}
/* …and inside the row, the textarea's own wrapper, which gradio stretches to the row
   height and then top-aligns the textarea within. That is the last 2px between the
   paperclip and the words it belongs to. ONE alignment property, no heights, no
   min-heights, nothing about the thumbnail — the cascade came from those, not from this. */
.chat-col .multimodal-textbox .textarea-wrapper {display: flex; align-items: center;}

/* The composer and the message bubbles are gradio's, untouched.
   Everything that used to be here reached inside them — an inline attachment row, a
   restyled thumbnail, textarea metrics, wrapper heights — and each fix created the next
   problem: the row changed the geometry, the geometry needed wrapper heights, the
   heights left the textarea with no slack, and a textarea with no slack showed a line
   that had been scrolled where no scrollbar could say so. Stock gradio has none of that
   because it is not fighting itself. What is left below styles only what this app owns:
   the group around the pair, the example rows, and the report panel. */

#example-scan button, #example-prompts button {text-align: left !important; justify-content: flex-start !important;}
/* One example per row. Gradio lays a gallery out as a wrapping flex ROW, so the three
   questions packed two-and-one and the shape of the block changed with the width of the
   words in it. A column reads as a list of choices, which is what it is. Left-aligned at
   their natural widths rather than stretched: full-width buttons would make a form out
   of three suggestions. */
#example-scan .gallery, #example-prompts .gallery {flex-direction: column !important;
    align-items: flex-start !important; gap: 8px !important;}
/* Both example rows at --t-control, the size every other control on the page uses.
   The scan example used to be var(--text-lg) — 16px against the question chips' 14 —
   from a time when the question chips rendered as markdown <p> and this one did not. */
#example-scan .gallery-item, #example-prompts .gallery-item {font-size: var(--t-control);}
@media (max-width: 900px) {
  .main-row {flex-direction: column !important;}
  .main-row .chat-col {flex-grow: 1 !important; flex-basis: auto !important; max-width: 100% !important;}
}

/* No divider between the columns: the conversation carries its own frame now, so the
   seam it was drawn to mark is already marked. */
@media (min-width: 901px) {
  .main-row:has(.report-col) .report-col {padding-left: 22px;}
}
/* A frame around the conversation AND the composer, because they are one surface: the
   messages and the thing you type into them belong to the same box, and framing only the
   message area made the composer read as a separate widget parked underneath. The empty
   state needs the frame at all because taking the placeholder away left a large white
   nothing with no edges — nobody can tell that is where the answers will appear.
   One hairline for the pair, one rule between them, no fill: the bubbles inside are
   white, and a filled box behind white bubbles is a box inside a box. */
.chat-col .chat-surface {border: 1px solid #e2e8f0 !important; border-radius: 8px;
    overflow: hidden; background: #ffffff;}
/* gradio renders a Group as a wrapper inside a wrapper and puts elem_classes on both, so
   the rule above landed twice and drew two touching hairlines — which reads as one heavy
   2px line, not as the hairline it was meant to be. */
.chat-col .chat-surface .chat-surface {border: 0 !important; border-radius: 0 !important;}
/* Inside the group, the children keep no borders of their own — the chatbot block ships
   a 3px #1e293b one, which drew a heavy dark rectangle around the message area the
   moment the two were grouped. The only line left inside is the one between the messages
   and the composer. */
.chat-col .chat-surface .block {border-width: 0 !important;}
/* One line at the seam. The composer already draws a top border inside the group, and
   this file was drawing a second one directly over it — two hairlines touching read as
   one heavy line. */
.chat-col .chat-surface .multimodal-textbox {border-radius: 0 !important;}

/* ── The chat column's controls, made to agree with each other ──────────────
   Everything below is one answer to the same question: the same kind of thing should
   look and behave the same way. Measured first, in every case.

   The two example rows were 42px and 44px tall at the same 14px and the same 6/12
   padding: gradio wraps a question example in an extra .container carrying its own
   4px 8px. Zeroed, so the rows differ by their words and nothing else. */
/* Hover, which neither row had. A chip that does not react to the pointer reads as a
   label, and these are the only things on the page a first visitor should click. */
#example-scan .gallery-item, #example-prompts .gallery-item {transition: background-color 0.15s ease;}
#example-prompts .gallery-item:hover {background: #f0fdfa; border-color: #99f6e4;}
#example-scan .gallery-item:hover {background: #115e59; border-color: #115e59;}
/* Attach and send sit in the same composer and had two different hovers: send lifted to
   grey, attach did nothing. Same surface now, and the same 8px corner as everything else. */
.chat-col .multimodal-textbox :is(button[aria-label*="Upload"], button[aria-label*="Submit"]) {
    border-radius: 8px; transition: background-color 0.15s ease;}
.chat-col .multimodal-textbox button[aria-label*="Upload"]:hover,
.chat-col .multimodal-textbox button[aria-label*="Submit"]:hover {background: #f0fdfa;}
/* The conversation's [delete][copy] and the report's [delete][copy][download] are two
   groups of the same idea in the same corner, drawn by two different mechanisms — one
   gradio's chatbot toolbar, one a gr.Button row. Same size, same grey, same hover. */
.chat-col .icon-button-wrapper button, #report-actions button,
#stop-button, #stop-button button,
.chat-col button[class*="scroll"], .chat-col [class*="scroll-down"] {
    border-radius: 8px !important; transition: background-color 0.15s ease;
    background: #ffffff !important; border: 1px solid #e2e8f0 !important;
    box-shadow: none !important; color: var(--body-text-color) !important;}
#stop-button:hover, #stop-button button:hover {background: #f0fdfa !important;}
/* No shadows and no movement on hover — the scroll-to-bottom button was doing both,
   which made it the only control on the page that jumped. */
.chat-col button[class*="scroll"]:hover, .chat-col [class*="scroll-down"]:hover {
    background: #f0fdfa !important; box-shadow: none !important; transform: none !important;}
.chat-col button:hover, #report-actions button:hover,
#example-scan .gallery-item:hover, #example-prompts .gallery-item:hover {
    box-shadow: none !important; transform: none !important;}
.chat-col .icon-button-wrapper button:hover, #report-actions button:hover {
    background: #f0fdfa !important;}

/* With a lease attached, "Attach a lease, or ask about renting in Washington…" is an
   instruction for something already done, sitting beside the chip that did it. :has()
   rather than a change event: the placeholder is presentation, and routing it through
   the server would put a round-trip between attaching a file and being able to type. */


footer {visibility: hidden;}

/* The example rows, in the report's label language. Gradio gives an Examples group a
   teal 14px semibold heading with a list glyph in front of it; the report's own
   section headings are 11px, uppercase, tracked, muted. Two ways of saying "this is a
   label" on one screen, and the louder one was on the less important thing — a heading
   in the accent colour outranked the findings it sat under. Same style for both now,
   and the glyph goes: it is decoration that reads as a control. */
#example-scan .label svg, #example-prompts .label svg {display: none;}
#example-scan .label, #example-prompts .label {font-size: var(--t-label); font-weight: 700;
    letter-spacing: 0.08em; text-transform: uppercase;
    color: var(--body-text-color-subdued) !important; gap: 0;}
/* Uniform chips. Their widths still differ — the questions are different lengths and
   padding them to a common width would be a grid of half-empty buttons — but the
   padding, border and radius no longer do. */
/* One box for both rows. The two disagreed twice: gradio wraps a question example in an
   extra .container with its own 4px 8px (42px against 44px), and zeroing that alone
   swung them the other way (42 against 36). So the line box is stated here rather than
   inherited from two different wrappers. */
#example-scan .gallery-item, #example-prompts .gallery-item {padding: 8px 12px;
    line-height: 20px;}
/* S4's one accent surface. This lives with the examples, not with the conversation: the
   example rows are this app's own markup, so styling them is not reaching into gradio. */
#example-scan .gallery-item, #example-prompts .gallery-item {background: #ffffff;
    border-color: #e2e8f0; color: var(--body-text-color);}
#example-scan .gallery-item {background: #0f766e; border-color: #0f766e; color: #ffffff;}
/* One green in the column, and it belongs to the action. The user's bubble was tinted in
   gradio's mint while the primary button is the app's teal — same hue family, two very
   different tints, which is what read as "not unified". This is a colour override and
   not a layout one: the composer bugs all came from the second kind. */
.chat-col .message.user {background: #ffffff !important;
    border-color: #e2e8f0 !important;}
/* The attached file's name, third copy of the same string: the context line had it as a
   markdown code chip, the report has it plain, and the bubble had it in gradio's mono.
   One typeface means one typeface — this is the last thing in the app that was not Inter. */
.chat-col .message code, .chat-col .message .md code {font-family: inherit !important;
    font-size: inherit !important; font-weight: 500; background: none !important;
    border: 0 !important; padding: 0 !important;}
/* font-size too, and that omission is why the rows still looked different after the
   last pass: a question example's words live in a <p>, and gradio's prose rules set that
   <p> to 16px directly — which outranks the 14px on the button it sits in. The scan
   example's words are a bare div and inherited the 14. Measured on the leaf node that
   actually holds the text, not on the button. */
#example-scan .gallery-item > div, #example-prompts .gallery-item .container,
#example-prompts .gallery-item p {padding: 0 !important; margin: 0 !important;
    font-size: var(--t-control) !important; line-height: 20px !important;}


/* The chatbot's toolbar sat in the same corner as the report's three actions and drew
   its icons in teal while those were grey. Same rule, two answers.
   `color` only. A `stroke: currentColor` here also painted the <rect> inside Gradio's
   trash glyph, which is meant to stay unstroked — the trash icon grew a box around it
   and the copy icon, which has no rect, did not. */
.chat-col .icon-button-wrapper button {color: var(--lh-muted, #94a3b8) !important;}
"""

# No 🧠. The wordmark's 🐕 is two lines above it, and two metaphors in one viewport is
# where a product starts looking like a demo. The hound's voice stays in the messages,
# which is where a voice belongs; this line is a status.
LAW_ONLY_CONTEXT = (
    "The hound knows **Washington tenant law (RCW 59.18)**. "
    "Scan a lease and it will know your report too."
)
ALREADY_SNIFFED = "🐕 Already sniffed this one — the report is still on the right."
# Everything before the first verdict: reading the document, splitting it, and the
# gate call. The pair to ask mode's "🐕 Thinking…", and short for the same reason —
# it is on screen for about a second, and a sentence nobody can finish reading before
# it is replaced is worse than no sentence. The first draft explained what the gate
# was doing and how the refusal worked, which was true, unreadable, and immediately
# followed by the refusal it was explaining.
#
# What it must NOT say is anything about clauses. For that second the UI used to show
# "0/N clauses sniffed" beside an opening report panel, so a document about to be
# refused had already been announced as a scan in progress and the refusal read as
# the app changing its mind. Nothing is claimed about the clauses until the gate has
# answered, and the panel does not open until the first verdict.
SNIFF_STARTING = "🐕 Sniffing…"
CACHED_SNIFF = (
    "🐕 The hound has sniffed this exact lease before — here's the saved report, "
    "no fresh API calls. Attach a different lease to watch a live scan."
)
CALLED_OFF = "🐕 Called off — the hound stopped mid-sniff. Scan again whenever you're ready."
# A locked PDF, which used to arrive as "the hound tripped over an error" — the generic
# handler, because pypdf raised before anything in this file could say anything better.
# Names the fix rather than the failure: nobody can do anything with "unsupported
# encryption", and everybody can print a PDF to a new PDF.
LOCKED_PDF = (
    "🐕 That PDF is locked with a password, so the hound can't open it at all. Nothing "
    "was scanned and nothing was spent. Print or export it as a new PDF — that copy "
    "opens — and attach that."
)
NOTHING_EXTRACTED = (
    "🐕 The hound couldn't find any text in this document — a scanned or photo PDF has "
    "no text layer. Try a text-based .pdf, .md, or .txt."
)
# The override the refusal below asks for. A phrase rather than a button because the
# upload is deleted as soon as its text is read (see cleanup_upload), so the document
# has to come back with the request — and a phrase the visitor types is unambiguously
# the visitor's, which is the property that keeps a planted "this is not a lease" line
# from suppressing anything on its own.
SCAN_ANYWAY_PHRASE = "scan anyway"

# Reaches the screen for two different documents — a guide about renting, and an
# `other` the reader insisted on — so it must not name either. Saying "a document
# about renting" here put that sentence above a scan of a banana bread recipe.
NOT_A_LEASE = (
    "🐕 The hound gave this a good sniff and it doesn't smell like a residential "
    "lease. Sniffing it anyway — but landlord-tenant verdicts on something that isn't "
    "a lease are unreliable, so read the report with that in mind."
)
# The refusal half. Says what it would take for a scan to mean anything, and points
# at the button — because the old warning claimed the scan happened "on request"
# when there was no way to make one.
NOT_ABOUT_RENTING = (
    "🛑 The hound had a good sniff and this doesn't smell like a lease **or** like "
    "anything about renting — no parties, no dwelling, no rent, no obligations. "
    "Judging it against landlord-tenant law would fill a page with confident "
    "nonsense, so nothing was judged and nothing was spent past the first look.\n\n"
    f"If it really is a lease, attach it again with **{SCAN_ANYWAY_PHRASE}** in the "
    "message. It has to be re-attached because your upload is deleted the moment its "
    "text is read — the hound doesn't keep a copy waiting for a second opinion."
)
# A different failure from NOT_A_LEASE, and it needs its own words: this document IS
# a residential lease, the gate is right to accept it, and what is wrong is the law
# being applied to it. Both directions of wrongness are spelled out because only one
# is intuitive — a reader expects "we may have missed something", not "the clause we
# flagged is fine where you live".
WRONG_STATE = (
    "🌎 This lease points to **{document} law**, and the hound only knows "
    "**Washington** (RCW 59.18). It'll finish the scan, but every section it cites "
    "will be a Washington statute that doesn't govern a {document} tenancy — so a red "
    "flag below may be perfectly enforceable where this lease actually lives, and a "
    "clause the hound calls clear may be void there with nothing in the report to say "
    "so. Read it as a Washington-shaped guess, not as a verdict on your rights."
)
# The ask-mode half of WRONG_STATE. Shorter, because there is no report to qualify —
# only the one answer that is about to arrive — and it has to name the consequence
# rather than the mechanism: a renter does not care which corpus is loaded, they care
# that the sentence they are about to read is about somebody else's state.
WRONG_STATE_QUESTION = (
    "🌎 You mentioned **{asked}**, and the hound only knows **Washington** law "
    "(RCW 59.18). Here's the Washington answer — but {asked} has its own landlord-"
    "tenant statutes, and on this question they may well say something different. "
    "Worth checking with a tenant-rights service where you actually rent."
)
PARTIAL_SCAN = (
    "🐕 This document splits into {count} clauses — long-form agreements really do run "
    "this long. The hound judges the first {limit}, so clauses {rest} won't get a verdict; "
    "the report says so too. The missing-protections check still reads the whole thing. "
    "Attach just the part you care about for full coverage."
)
# The other end of the same size question, and the one that has an answer instead of a
# degraded scan: see scan.DocumentTooLarge for why this is refused where the clause cap
# only trims. Phrased in pages because nobody uploading a lease thinks in characters.
TOO_LARGE = (
    "🐕 That file is too big for one scan — about {pages} pages of text, and the hound "
    "reads up to roughly {limit}. Nothing was scanned and nothing was spent. A residential "
    "lease is almost never this long, so this is usually a whole document bundle: attach "
    "just the lease or the section you care about."
)
# Measured, not guessed — the first draft of this line said 1800 and was wrong by most
# of a page. Across the five real published leases in eval_real_formats.py the extracted
# text runs 2,666–5,820 characters per PDF page (median 3,130); the outlier is the HUD
# addendum, whose 5 pages are unusually dense. 3000 puts the limit at ~128 pages.
#
# The copy says "about" and this stays a round number on purpose: the job is to give a
# visitor a sense of scale, not a figure they could hold the scan to.
CHARS_PER_PAGE = 3000

# The ask side of the same size question. A question is not a file, which is exactly why
# it went unbounded: the four spend bounds in the README were all about scans, and the
# one route that did cap a question — /v1/ask, at the same 2,000 characters — is the one
# that returns 503 on the hosted demo. Characters here, not pages: somebody who pastes
# this much into a chat box knows they pasted a lot.
QUESTION_TOO_LONG = (
    "🐕 That's a lot to read in one go — {chars} characters, and the hound takes up to "
    "{limit} per question. Nothing was spent. Ask about one clause or one situation at a "
    "time and the answers get sharper anyway; if it's a whole document, attach it with "
    "the paperclip and let the hound scan it instead."
)
# How much of a scan report rides along in ask mode's context. Imported by nothing else
# here on purpose: it IS answer.MAX_HISTORY_MESSAGE_CHARS, because the report is the
# largest message this pipeline legitimately produces and there is no second opinion to
# have about it. Before, this was a bare 6000 in answer_flow while /v1/ask accepted
# 200,000 — the same context under two limits 33x apart, neither derived from the other.
REPORT_CONTEXT_CHARS = MAX_HISTORY_MESSAGE_CHARS


def in_pages(chars: int) -> str:
    return f"{max(1, round(chars / CHARS_PER_PAGE)):,}"
HOUND_TRIPPED = (
    "🐕 The hound tripped over an error and lost the scent — nothing was changed. "
    "Try again, or try a different file."
)
# The example chip shows the file name; once clicked, the file rides along as an
# attachment, so the message itself drops the "(sample_lease.md)" suffix.
SCAN_EXAMPLE = {
    "text": "Sniff this sample lease for red flags",
    "files": [str(SAMPLE_LEASE)],
}
SCAN_EXAMPLE_LABEL = "Sniff this sample lease for red flags (sample_lease.md)"
QUESTION_EXAMPLES = [
    {"text": "Can my landlord charge a late fee if rent is 3 days late?", "files": []},
    {"text": "How much notice before my landlord can enter?", "files": []},
    {"text": "When do I get my security deposit back after moving out?", "files": []},
]


def report_context(name: str) -> str:
    # The pair to LAW_ONLY_CONTEXT, and emoji-free for the same reason: this is the
    # status line above the conversation, not the hound talking.
    # Both runs are complete noun phrases, article and all: "the" sitting outside the
    # bold made one half look like a different kind of thing from the other.
    return f"The hound knows **Washington tenant law** + **the scan report of {name}**."


# No --- divider: markdown gives an <hr> generous margins on top of the
# paragraph gap, which reads as a hole between the answer and its sources.
# "Statutes cited:" — right under the answer, "in this answer" says nothing.
FOOTER_MARK = "\n\n**Statutes cited:**"
# A model-written imitation of the footer (any trailing "Statutes cited …"
# block, however formatted or worded) — stripped before the real one is appended.
MODEL_FOOTER = re.compile(
    r"\n+(?:-{3,}\n+)?\**Statutes cited(?: in this answer)?:?\**[\s\S]*\Z"
)


def sources_footer(answer: str, chunks) -> str:
    """List only the statutes the answer actually cites, not everything retrieved.

    An off-topic question still retrieves (irrelevant) chunks, and the answer
    honestly declines — the footer shouldn't then present those chunks as
    sources. Cited = mentioned in the answer AND present in the retrieved set.
    """
    url_by_section = {}
    for chunk in chunks:
        section = chunk.metadata.get("section")
        if section:
            url_by_section.setdefault(section, chunk.metadata.get("url", ""))
    seen, lines = set(), []
    for section in re.findall(r"RCW \d+\.\d+\.\d+", answer):
        if section in url_by_section and section not in seen:
            seen.add(section)
            url = url_by_section[section]
            lines.append(f"- [{section}]({url})" if url else f"- {section}")
    return FOOTER_MARK + "\n" + "\n".join(lines) if lines else ""


def strip_footer(message: dict) -> dict:
    """Drop the sources footer from an assistant message before it re-enters the LLM.

    The footer is display chrome. Fed back as conversation history, the model
    learns the pattern and writes its own copy at the end of the next answer —
    which then gets the real footer appended below it, doubling the block.
    """
    content = message.get("content")
    if message.get("role") == "assistant" and isinstance(content, str) and FOOTER_MARK in content:
        return {**message, "content": content.split(FOOTER_MARK)[0].rstrip()}
    return message


def cleanup_upload(path: Path) -> None:
    """Delete an uploaded temp file as soon as its text is extracted (privacy)."""
    if path != SAMPLE_LEASE and str(path).startswith(tempfile.gettempdir()):
        path.unlink(missing_ok=True)


# Cross-visitor scan cache, keyed by document CONTENT — not upload path, which
# is unique per upload, and not session, which is one browser tab. Most demo
# traffic scans the one sample lease; only its first scan after a cold start
# should cost API calls. Memory only (never disk), bounded, gone with the
# instance — the next first scan re-warms it. Stores findings + protections
# rather than the rendered report so a hit renders under its own file name.
CACHE_MAX_ENTRIES = 32
_scan_cache: OrderedDict[str, dict] = OrderedDict()
_scan_cache_lock = threading.Lock()


def cache_key(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", "replace")).hexdigest()


def cache_get(digest: str) -> dict | None:
    with _scan_cache_lock:
        entry = _scan_cache.get(digest)
        if entry is not None:
            _scan_cache.move_to_end(digest)
        return entry


def cache_put(digest: str, entry: dict) -> None:
    with _scan_cache_lock:
        _scan_cache[digest] = entry
        _scan_cache.move_to_end(digest)
        while len(_scan_cache) > CACHE_MAX_ENTRIES:
            _scan_cache.popitem(last=False)


def progress_line(done: int, total: int) -> str:
    return f"🐕 On the scent — {done}/{total} clauses sniffed…"


# The one thing in this app that really does write lease-derived content to disk — the
# report quotes the clauses it judged — and it has to, because a download button can only
# serve a file. What it must not do is keep them: this made a fresh temp directory per
# finished scan and deleted none of them, so a long-lived instance accumulated every
# report it had ever rendered. On Cloud Run that is not a disk, it is a slice of the same
# 1 GiB the scan is running in.
#
# A subdirectory per report rather than one directory of files, because the file NAME is
# the visitor's own and two visitors uploading `lease.pdf` must not be able to hand each
# other a report. Pruning is oldest-first and generous enough that a download stays valid
# far longer than anyone waits before clicking: 32 more scans have to finish first, the
# same bound and the same reasoning as the scan cache above.
REPORTS_ROOT = Path(tempfile.mkdtemp(prefix="leasehound_reports_"))
MAX_REPORT_FILES = CACHE_MAX_ENTRIES
_report_lock = threading.Lock()


def report_file(report: str, source_name: str) -> str:
    """Write the report where the download button can serve it, and prune the rest."""
    with _report_lock:
        REPORTS_ROOT.mkdir(parents=True, exist_ok=True)
        folder = Path(tempfile.mkdtemp(dir=REPORTS_ROOT))
        path = folder / f"scan_report_{Path(source_name).stem}.md"
        path.write_text(report, encoding="utf-8")
        stale = sorted(REPORTS_ROOT.iterdir(), key=lambda d: d.stat().st_mtime)
        for folder_to_drop in stale[:-MAX_REPORT_FILES]:
            shutil.rmtree(folder_to_drop, ignore_errors=True)
    return str(path)


# Every event yields the same 10 outputs. `col` shows/hides the report column, so
# the page is a single centered chat until there is something to pin. The input
# box is disabled while a scan runs — a submit queued mid-scan would carry a
# pre-scan snapshot of the cache state and silently rescan. `actions` is the
# [copy][download][trash] row: one switch so the three buttons always appear
# together, only once a finished report is pinned. `download` carries the file.
# [chatbot, message_box, report_output, report_state, context_line,
#  scanned_source, stop_button, report_col, download_button, report_actions]


def _out(history=gr.skip(), box=gr.skip(), report=gr.skip(), state=gr.skip(),
         context=gr.skip(), source=gr.skip(), stop=gr.skip(), col=gr.skip(),
         download=gr.skip(), actions=gr.skip()):
    return history, box, report, state, context, source, stop, col, download, actions


def answer_flow(question, history, report, context_base):
    """Append the hound's answer to an already-appended user message."""
    history.append({"role": "assistant", "content": "🐕 Thinking…"})
    yield _out(history)
    # Trim BEFORE prepending, so the report survives; strip footers so the
    # model doesn't mimic them (see strip_footer).
    #
    # `[-10:]` bounds how many messages the model sees and nothing about how big they
    # are, which is the same sentence as MAX_CLAUSES bounding the clause count and
    # nothing about the document. The size bound lives in answer_question, because
    # this handler is not the only door — Gradio publishes it as an unauthenticated
    # HTTP endpoint, and `history` is then whatever the caller sends.
    context_history = [strip_footer(m) for m in list(context_base)[-10:]]
    if report:
        context_history = [
            {
                "role": "user",
                "content": ("For context, here is the scan report of my lease:\n\n"
                            + report[:REPORT_CONTEXT_CHARS]),
            },
            {
                "role": "assistant",
                "content": "Got it — I'll answer your questions with your scan report in mind.",
            },
        ] + context_history
    try:
        answered = answer_question(question, context_history, report_context=bool(report))
    except QuestionTooLong as long_question:
        # Refused, not truncated: answering half a question answers a different
        # question. Costs $0 — the check runs ahead of the router, which is ask mode's
        # first API call.
        history[-1]["content"] = QUESTION_TOO_LONG.format(
            chars=f"{long_question.chars:,}", limit=f"{long_question.limit:,}")
        yield _out(history, box=gr.update(interactive=True))
        return
    # `routed` guards it: the warning is about the ANSWER being Washington law, and the
    # chitchat path has no legal content to be wrong about. "Hi, I'm in Oregon" would
    # otherwise get a paragraph about which statutes the hound carries in reply to a
    # greeting.
    if answered.routed and jurisdiction_mismatch(answered.jurisdiction, DEMO_STATE):
        # Above the answer, not below it: a renter reading "your landlord cannot do
        # that" has already acted on it by the time they reach a footnote. Inserted
        # rather than replacing "🐕 Thinking…", because the answer is still coming —
        # it is the Washington answer, which is not nothing, it is just not theirs.
        history.insert(-1, {"role": "assistant", "content": WRONG_STATE_QUESTION.format(
            asked=answered.jurisdiction.upper())})
        yield _out(history)
    answer = ""
    for delta in answered.stream:
        answer += delta
        history[-1]["content"] = answer
        yield _out(history)
    answer = MODEL_FOOTER.sub("", answer).rstrip()
    history[-1]["content"] = answer + sources_footer(answer, answered.chunks)
    yield _out(history)


def scan_flow(path, key, history, report, scanned, context_base, question="",
              scan_anyway=False):
    """Scan a lease with per-clause progress in chat; report lands in the side panel."""
    name = path.name
    # `scan_anyway` skips both caches deliberately. Refusals are not cached today,
    # so a miss is what would happen anyway — but an override whose correctness
    # depends on that staying true is one refactor away from silently doing nothing,
    # and "scan anyway" has to mean a scan happened.
    if scanned == key and report and not scan_anyway:
        history.append({"role": "assistant", "content": ALREADY_SNIFFED})
        # `report` here is the stored markdown, and re-rendering HTML would need the
        # findings, which this path does not have. The panel already shows this very
        # report — on_trash clears panel and state together, so they cannot disagree.
        yield _out(history, report=gr.skip(), state=report,
                   context=report_context(name), source=key,
                   stop=gr.update(visible=False), col=gr.update(visible=True),
                   download=gr.update(value=report_file(report, name)),
                   actions=gr.update(visible=True))
        if question:
            yield from answer_flow(question, history, report, context_base)
        return

    # read_document is called OUTSIDE the try that wraps the scan, which is why the
    # EncryptedDocument handler added below it never fired: a locked PDF raised here and
    # went straight to respond()'s generic "tripped over an error". Found by uploading one
    # to the deployed revision — the fix for the message was in the wrong function.
    try:
        text = read_document(path)
    except EncryptedDocument:
        cleanup_upload(path)
        history.append({"role": "assistant", "content": LOCKED_PDF})
        # Nothing on the right is touched: the file never opened, so whatever report is
        # on screen is still the current one.
        yield _out(history, box=gr.update(interactive=True))
        return
    cleanup_upload(path)

    digest = cache_key(text)
    result = cache_get(digest) if not scan_anyway else None
    if result is not None:
        log_scan(UsageMeter(), name, result.clauses_judged,
                 verdicts=count_verdicts(result.findings),
                 missing=missing_protections(result), split_mode=result.split_mode,
                 cache_hit=True, clauses_total=result.clauses_total, client="ui")
        history.append({"role": "assistant", "content": CACHED_SNIFF})
        # The report carries the jurisdiction warning either way, but a cached scan
        # skips every step that narrates one — so the second visitor to attach a
        # California lease saw it only if they opened the panel, while the first was
        # told in chat. Same document, same finding, two different experiences.
        if jurisdiction_mismatch(result.jurisdiction, DEMO_STATE):
            history.append({"role": "assistant", "content": WRONG_STATE.format(
                document=result.jurisdiction.upper())})
        yield from finished_scan(result, name, key, history, context_base, question)
        return

    # Everything below is `scan.scan_steps` narrating itself into chat. The steps —
    # split, gate, each clause, protections — are the pipeline's, not this file's:
    # this function used to re-assemble them from the same primitives the CLI uses,
    # and two copies of a sequence that spends money stay in step only by luck.
    history.append({"role": "assistant", "content": SNIFF_STARTING})
    # A fresh scan makes any previous report stale immediately: law-only context until the
    # new report lands, and the stale report comes off the panel at once.
    #
    # The COLUMN, though, stays where it is. It used to close here and reopen a second
    # later, so uploading a second lease made the whole page collapse to one column and
    # slide back out — a 900ms rearrangement of everything on screen to report progress
    # that the chat was already narrating. Now the split survives the scan, including a
    # refusal: the panel says what happened and the layout holds. Only the trash closes
    # it, which is the one case where the user asked for the report to be gone.
    # Nothing on the right is touched until there is something to put there. The column
    # used to close and reopen — a 900ms rearrangement of the page to report progress the
    # chat was already narrating — and then it cleared the panel, the state and the
    # context, so a lease that failed to open cost you the report you already had. Both
    # were the same mistake: treating "a new scan started" as "the old result is gone".
    # It is gone when it is replaced (finished_scan) or when the trash says so.
    yield _out(history, box=gr.update(interactive=False),
               stop=gr.update(visible=True),
               col=gr.skip() if report else gr.update(visible=False))
    try:
        for step in scan_steps(text, name, state=DEMO_STATE, scan_anyway=scan_anyway,
                               client="ui"):
            if step.kind == "judging":
                # The gate has accepted, so this is the first moment a scan may be
                # promised. Over the cap it goes ahead on a prefix — refusing meant a
                # visitor who uploaded a real WA housing agreement (270 clauses) got
                # nothing at all, which is worse than 60 judged clauses that say which
                # 210 they aren't. Keyed off `judging` and not `split` because a long
                # document that was about to be refused used to be told which 60 of its
                # clauses would be judged, and only then told it was not a lease.
                if step.partial:
                    history.insert(-1, {"role": "assistant", "content": PARTIAL_SCAN.format(
                        count=step.total, limit=MAX_CLAUSES,
                        rest=f"{step.judged + 1}–{step.total}")})
                # And the panel opens here rather than on the first verdict, which is
                # what it had to key on before this step existed. 0/N is honest now:
                # it appears only once N clauses are certain to be judged.
                history[-1]["content"] = progress_line(0, step.judged)
                yield _out(history, col=gr.update(visible=True),
                           report=f'<p class="lh-waiting">Sniffing '
                                  f'<code>{escape(name)}</code> — the report will '
                                  f'appear here.</p>')
            elif step.kind == "gate_flagged":
                history.insert(-1, {"role": "assistant", "content": NOT_A_LEASE})
                yield _out(history)
            elif step.kind == "jurisdiction":
                history.insert(-1, {"role": "assistant", "content": WRONG_STATE.format(
                    document=step.document_state.upper())})
                yield _out(history)
            elif step.kind == "gate_refused":
                # Replaces the progress line rather than sitting above it: there is
                # no progress to narrate, and leaving "judging clause 0 of N" on
                # screen would promise a scan that is not going to happen.
                history[-1]["content"] = NOT_ABOUT_RENTING
                yield _out(history)
            elif step.kind == "clause":
                history[-1]["content"] = progress_line(step.judged, step.total)
                yield _out(history)
            elif step.kind == "protections":
                history[-1]["content"] = (
                    "🐕 One more pass — checking the protections the law requires…")
                yield _out(history)
            elif step.kind == "done" and step.result.refused:
                # `step.kind == "done"` is named rather than left to an `else`. It used
                # to be one, and when the cap notice moved off `split` that step fell
                # through to here and dereferenced a `result` that is None on every
                # step but the last. A caller with nothing to say about a step kind
                # should ignore it, not crash on the way to the result.
                #
                # Not cached, and no panel pinned. The cache serves finished
                # reports and a hit is rendered as one, so keeping refusals out of
                # it costs one cheap classification call and keeps every other
                # path uniform. Leaving the context on law-only matters more:
                # telling ask mode "you have the scan report of X" when no clause
                # was judged would invent a report for it to reason from.
                # A refusal is a no-op for everything on the right: the report you
                # already had, its state, its context and its buttons all stay exactly as
                # they were. This used to clear all four and print "nothing judged" in the
                # panel, which charged a bad upload the price of your last good one.
                yield _out(history, box=gr.update(interactive=True),
                           stop=gr.update(visible=False))
            elif step.kind == "done":
                cache_put(digest, step.result)
                history[-1]["content"] = scan_summary(step.result)
                yield from finished_scan(step.result, name, key, history,
                                         context_base, question)
    except NoTextExtracted:
        history[-1]["content"] = NOTHING_EXTRACTED
        yield _out(history, box=gr.update(interactive=True),
                   stop=gr.update(visible=False))
    except DocumentTooLarge as oversized:
        history[-1]["content"] = TOO_LARGE.format(
            pages=in_pages(oversized.chars), limit=in_pages(oversized.limit))
        yield _out(history, box=gr.update(interactive=True),
                   report="", state="", context=LAW_ONLY_CONTEXT, source="",
                   stop=gr.update(visible=False), col=gr.update(visible=False),
                   actions=gr.update(visible=False))


def missing_protections(result: ScanResult) -> int:
    return sum(1 for p in result.protections if p["status"] == "missing")


def scan_summary(result: ScanResult) -> str:
    coverage = (f" — across clauses 1–{result.clauses_judged} of {result.clauses_total}"
                if result.partial else "")
    # summary_counts, the same function the panel's chips and the .md report are built
    # from, so all three name the counts identically — this line used to write its own
    # "7 red" beside a chip reading "7 red flags".
    #
    # And no 🚩⚠️🔍✅. The panel expresses these four counts as coloured chips two
    # inches to the right; expressing them again as four emoji, in a different order of
    # visual weight, is the same data in two languages on one screen. The hound keeps
    # its own emoji — the voice is deliberate — but one per message, not five.
    row = ", ".join(label for _, label in
                    summary_counts(result.findings, result.protections))
    return (
        f"🐕 Sniff complete{coverage}: {row}. "
        "Full report on the right — ask me about any clause."
    )


def finished_scan(result: ScanResult, name, key, history, context_base, question):
    """Pin the report and settle the panel — the caller has already said its piece
    in chat. Shared by the fresh and the cached path, which had drifted to calling
    `render_report` with different arguments for the same report."""
    args = (result.findings, name, DEMO_STATE, result.protections,
            result.gate_flagged, result.clauses_total)
    report = render_report(*args, jurisdiction=result.jurisdiction)
    # The panel gets HTML; `state` and the download keep the markdown, because the
    # chat reads the report as context and the download serves it as a .md file.
    panel = render_report_html(*args, jurisdiction=result.jurisdiction, markdown=report)
    yield _out(history, box=gr.update(interactive=True),
               report=panel, state=report,
               context=report_context(name), source=key,
               stop=gr.update(visible=False), col=gr.update(visible=True),
               download=gr.update(value=report_file(report, name)),
               actions=gr.update(visible=True))
    if question:
        yield from answer_flow(question, history, report, context_base)


def respond(message, history, report, scanned):
    """Guard around the real handler: an uncaught exception inside a generator
    event dies silently — the traceback goes to the server log and the user
    sees nothing happen at all (how a missing PDF dependency shipped). Turn any
    failure into a hound apology and restore the pre-turn panel state."""
    history = list(history)
    try:
        yield from _respond(message, history, report, scanned)
    except Exception:
        traceback.print_exc()
        history.append({"role": "assistant", "content": HOUND_TRIPPED})
        name = SAMPLE_LEASE.name if scanned == "sample" else Path(scanned).name
        yield _out(history, box=gr.update(interactive=True),
                   report=gr.skip(), state=report,
                   context=report_context(name) if report else LAW_ONLY_CONTEXT,
                   source=scanned, stop=gr.update(visible=False),
                   col=gr.update(visible=bool(report)),
                   actions=gr.update(visible=bool(report)))


def _respond(message, history, report, scanned):
    text = (message.get("text") or "").strip()
    files = message.get("files") or []
    if not text and not files:
        yield _out(box=gr.update(value=None))
        return
    context_base = list(history)  # snapshot before this turn's messages
    if files:
        path = Path(files[0])
        if path.name == SAMPLE_LEASE.name:
            # The sample-lease example: scan the repo file itself and cache as "sample".
            path, key = SAMPLE_LEASE, "sample"
        else:
            key = str(path)
        user_content = f"📎 `{path.name}`" + (f"\n\n{text}" if text else "")
        history.append({"role": "user", "content": user_content})
        yield _out(history, box=gr.update(value=None))
        # The canned example text is an instruction the scan itself fulfills —
        # don't answer it again as a follow-up question afterwards.
        question = "" if text == SCAN_EXAMPLE["text"] else text
        anyway = SCAN_ANYWAY_PHRASE in text.lower()
        # It was the override, not a question — answering "scan anyway" as a legal
        # question afterwards would be nonsense.
        if anyway:
            question = ""
        yield from scan_flow(path, key, history, report, scanned, context_base,
                             question=question, scan_anyway=anyway)
    else:
        history.append({"role": "user", "content": text})
        yield _out(history, box=gr.update(value=None))
        yield from answer_flow(text, history, report, context_base)


def on_stop(history):
    history = list(history)
    if history and history[-1]["role"] == "assistant":
        history[-1]["content"] = CALLED_OFF
    # The report was already invalidated at scan start, so the panel column
    # disappears again rather than showing a stale "scanning…" line.
    return (history, gr.update(interactive=True), "", gr.update(visible=False),
            gr.update(visible=False), gr.update(visible=False))


def on_trash():
    """Discard the pinned report: back to a law-only, solo-chat page.

    Silent, matching the chatbot's built-in clear button — the column
    collapsing and the context line reverting are feedback enough. (A chat
    message would merge into the previous assistant bubble and pollute the
    answering context; a toast would be this app's only toast.)
    """
    # TRASH_JS is sliding both columns to their solo positions right now; wait
    # it out so the DOM removal lands after the columns have stopped moving.
    time.sleep(0.5)
    return ("", "", LAW_ONLY_CONTEXT, "", gr.update(visible=False),
            gr.update(visible=False))


# Copy is client-side only — no server round-trip. Feedback: the copy icon
# itself becomes a checkmark in place for a moment (swapping the img src to a
# data URI; a check.svg on disk wouldn't be on Gradio's allowed-files list).
# Selected by the button's own id, not by its place in the row: this read
# `#report-actions button img` — the first button — and the checkmark moved to the
# delete icon the moment the row was reordered.
# The js handler must return a list (Gradio maps it to outputs).
CHECK_ICON = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" '
    'stroke="#6b7280" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
    '<polyline points="20 6 9 17 4 12"/></svg>'
)
# Reads the markdown out of the hidden field report_html.py leaves in the panel,
# not the panel's own value: that value is now HTML, and copying markup is not what
# this button promises. A gr.State would be the obvious home for the markdown, but a
# js-only handler runs entirely client-side and gr.State values only exist on the
# server — the same constraint that used to point this at the Markdown component.
COPY_JS = f"""
() => {{
    const field = document.querySelector('.report-panel .lh-md');
    navigator.clipboard.writeText(field ? field.value : '');
    const img = document.querySelector('#copy-report img');
    if (img) {{
        if (!img.dataset.copyIcon) img.dataset.copyIcon = img.src;
        img.src = 'data:image/svg+xml;utf8,' + encodeURIComponent({CHECK_ICON!r});
        setTimeout(() => {{ img.src = img.dataset.copyIcon; }}, 1200);
    }}
    return [];
}}
"""

# Examples send on click — one click, one message, like example chips in chat
# apps; they're complete questions, there's nothing to edit first. Gradio's
# Examples component only fills the box (run_on_click can't pass the state
# inputs respond needs), so a page-level listener waits for the fill to land
# and clicks send. The scan example also attaches a file — wait for its chip,
# or the submit would race the attachment and send text alone.
EXAMPLES_JS = """
() => {
    // Put the cursor in the message box on load, so a visitor can start typing
    // without clicking first. Deliberately not Gradio's autofocus=True: that
    // scrolls the focused input into view, measured at 713px down, which pushes
    // the wordmark and the one-click scan example off the top of the page.
    // preventScroll buys the focus without the jump.
    let focusTries = 0;
    const focusBox = setInterval(() => {
        const input = document.querySelector('.chat-col .multimodal-textbox textarea');
        if (input) {
            input.focus({preventScroll: true});
            clearInterval(focusBox);
        } else if (++focusTries > 40) {
            clearInterval(focusBox);
        }
    }, 50);

    document.addEventListener('click', (event) => {
        const chip = event.target.closest('#example-scan button, #example-prompts button');
        if (!chip) return;
        const needsFile = !!chip.closest('#example-scan');
        let tries = 0;
        const timer = setInterval(() => {
            const box = document.querySelector('.chat-col .multimodal-textbox');
            const filled = box.querySelector('textarea').value.trim()
                && (!needsFile || box.querySelector('.thumbnail-item'));
            if (filled) {
                clearInterval(timer);
                box.querySelector('.submit-button').click();
            } else if (++tries > 60) {
                clearInterval(timer);
            }
        }, 50);
    });
}
"""

# Two things the app keeps doing for the composer, both content rather than layout: an
# empty textarea whose
# scrollTop is not zero shows its placeholder with the top sheared off, and
# `overflow-y: hidden` means no scrollbar appears to explain it. Reproduced by setting
# scrollTop to 6 and matching the screenshot pixel for pixel. Three lines, no layout,
# and it only ever fires when there is nothing to scroll to.
COMPOSER_JS = """
() => {
    const EMPTY = "Attach a lease, or ask about renting in Washington…";
    const ATTACHED = "Ask about this lease, or press send to scan it";
    const fix = (t) => { if (t && t.tagName === 'TEXTAREA' && !t.value && t.scrollTop) t.scrollTop = 0; };
    const sync = () => {
        const box = document.querySelector('.chat-col .multimodal-textbox');
        if (!box) return;
        const input = box.querySelector('textarea');
        fix(input);
        // Attribute only. Everything else that used to live here — the cloned glyph, the
        // inline row, the wrapper heights — is what the retreat to stock gradio removed,
        // and none of it is coming back. A placeholder still asking for a lease while the
        // lease sits next to it is a content bug, and content is this app's to fix.
        if (input) input.placeholder = box.querySelector('.thumbnail-item') ? ATTACHED : EMPTY;
    };
    for (const type of ['scroll', 'input', 'change', 'blur', 'focus']) {
        document.addEventListener(type, (e) => fix(e.target), true);
    }
    setInterval(sync, 300);
    sync();
}
"""

# Starts the two-columns-to-one slide immediately on click; on_trash sleeps
# past the transition before removing the report column from the DOM. The
# class comes off on a timer (the column is long gone by then) so a future
# report isn't born collapsed.
TRASH_JS = """
() => {
    const row = document.querySelector('.main-row');
    if (row) {
        row.classList.add('closing');
        setTimeout(() => row.classList.remove('closing'), 700);
    }
    return [];
}
"""


# Gradio 6 moved theme/css/js off the Blocks constructor. Theme and css belong to
# whoever serves the Blocks, and there are two of those — `launch()` here and
# `mount_gradio_app()` in api.py — so they live in one dict rather than being
# spelled out twice and drifting.
#
# `js` is deliberately NOT in here. Passing it to launch() is accepted and then
# silently never runs: the script is absent from the page and activeElement stays
# on <body>, which killed both the autofocus and the click handler that makes the
# example chips submit. It has to be a load event instead (see demo.load below).
UI_STYLE = {
    # One corner radius for the whole app, set as tokens rather than in CSS so every
    # control Gradio draws picks it up — including the ones this app never names.
    #
    # Measured before touching it, on the live page: message blocks 4px, example
    # buttons 6px, the composer 0px, the report's findings 10px, verdict chips 999px.
    # Five radii in one viewport. Nobody reads a radius, but the eye counts corners,
    # and five kinds of corner is most of what "杂乱" is made of.
    #
    # 8px is Soft's own radius_lg, so it is a value the theme already contains rather
    # than one invented here. Two radii survive: 8px for anything rectangular, and
    # 999px for the verdict chips, which are pills — a different shape, not a
    # different radius.
    "theme": gr.themes.Soft(
        primary_hue="teal",
        neutral_hue="slate",
        font=[gr.themes.GoogleFont("Inter"), "ui-sans-serif", "system-ui", "sans-serif"],
    ).set(
        block_radius="*radius_lg",
        container_radius="*radius_lg",
        input_radius="*radius_lg",
        button_large_radius="*radius_lg",
        button_medium_radius="*radius_lg",
        button_small_radius="*radius_lg",
        # White surface, filled boxes — the card's own polarity, which the first attempt
        # at this had backwards. The card is a #ffffff window whose contents are FILLED:
        # chips #f8fafc, the finding block #fffbfb, both a shade darker than the surface
        # they sit on. That version made the page #eef2f6 and the boxes white, which is
        # a layer either way, but the wrong way round: white is the brightest colour
        # available, so putting it on the small elements makes every box step forward
        # and the page compete with its own content. Brightest on the largest area,
        # content boxes a shade back.
        # Light only: the *_dark tokens resolve separately, and the dark theme's
        # near-black page already has more contrast against its blocks than this does.
        body_background_fill="#ffffff",
        border_color_primary="#dbe2ea",
    ),
    "css": CSS,
}

# Name, then what it is — one shape for the tab, the link preview and the share card,
# which is why this is one string and not two.
#
# It used to be the wordmark alone, on the reasoning that a crowded tab shows about 20
# characters. That reasoning was only half the picture: the same string is the
# bookmark, the history entry and the tab's tooltip, and in all three the gloss is the
# part that tells someone what the bookmark was for. A tab strip truncates the tail,
# so "LeaseHound" survives crowding either way and the gloss is a free win when there
# is room.
SOCIAL_TITLE = "LeaseHound — lease red-flag scanner"

with gr.Blocks(title=SOCIAL_TITLE) as demo:
    gr.HTML(HERO)
    report_state = gr.State("")
    scanned_source = gr.State("")  # what the current report is for: a file path or "sample"

    with gr.Row(elem_classes="main-row"):
        with gr.Column(scale=1, elem_classes="chat-col"):
            context_line = gr.Markdown(LAW_ONLY_CONTEXT, elem_classes="step-sub")
            # Gradio 6 dropped `type=`: the messages format this app already uses
            # is the only one now, so the argument became a no-op and then an error.
            # Gradio's default toolbar is ["share", "copy_all"], and its "share"
            # posts to Hugging Face Spaces Discussions — a no-op anywhere else, so
            # on Cloud Run it is a button that cannot do anything. Naming the list
            # drops it and keeps the ones that work.
            #
            # "copy" is gone from that list: it hangs a copy icon under EVERY message,
            # and with two messages on screen that was three floating icons — the
            # per-message ones plus the toolbar's — at three different left edges, the
            # loudest non-content thing on the page. copy_all stays, in the toolbar at
            # the top-right, which is the same corner the report's own actions sit in.
            # One place where actions live.
            #
            # No placeholder. There was one — "Findings appear here, each citing a
            # statute." — and it sat directly above the composer's own "Attach a lease,
            # or ask about renting in Washington…", two hints competing for the same
            # glance. The composer's is attached to the thing you actually type in, so
            # it is the one that survives.
            #
            # A FIXED height, deliberately. It was briefly min 180 / max 440 so the box
            # would hug short conversations, and the cost was worse than the empty
            # surface it saved: the box resized on every turn, so the composer and the
            # examples under it moved while the reader was mid-sentence. A stable frame
            # beats a tight one in the one region the eye is already fixed on.
            #
            # The height is min(420px, 45vh) rather than a pixel count, and the hero gives
            # up 16px of padding to the same cause: what has to fit above the fold is the
            # first example plus enough of the next one to say "there is more", and the
            # fold moves. On a 13" MacBook in Chrome it is around 780px fullscreen and
            # about 720 in a window; at a fixed 440 the first example fell 14px below the
            # fold and the page appeared to end inside a button, and at a fixed 380 the
            # windowed case still cleared it by 2px. A viewport fraction fits both, and it
            # is still FIXED in the sense that matters — it does not move while messages
            # arrive, only when the window itself changes. The 420 cap keeps a large
            # monitor from turning the conversation into a canyon.
            #
            # One gr.Group around the pair: the messages and the thing you type into
            # them are one surface, and a frame around only the message area made the
            # composer look like a separate widget that happened to sit below it.
            with gr.Group(elem_classes="chat-surface"):
                chatbot = gr.Chatbot(height="min(420px, 45vh)", show_label=False,
                                     buttons=["copy_all"])
                message_box = gr.MultimodalTextbox(
                    placeholder="Attach a lease, or ask about renting in Washington…",
                    show_label=False,
                    file_types=[".pdf", ".md", ".txt"],
                    file_count="single",
                    # Cursor lands here on load: asking is the zero-friction entry
                    # point, and the scan button is one click away either way.
                )
            gr.Examples(
                examples=[SCAN_EXAMPLE],
                example_labels=[SCAN_EXAMPLE_LABEL],
                inputs=message_box,
                label="Scan a lease",
                elem_id="example-scan",
            )
            gr.Examples(
                examples=QUESTION_EXAMPLES,
                inputs=message_box,
                label="Ask a question",
                elem_id="example-prompts",
            )
        with gr.Column(scale=1, visible=False, elem_classes="report-col") as report_col:
            # No variant="stop": that painted it in gradio's red, the only red control in
            # an app where red means "this clause is a red flag". It is an ordinary
            # secondary button and hovers like every other one.
            stop_button = gr.Button(
                "✋ Call off the hound", size="sm", visible=False,
                elem_id="stop-button",
            )
            # One row pinned at the panel's top-right corner (see the CSS), so
            # all three actions share the same position and appear together,
            # only once a finished report is up.
            # Discard, copy, download — matching the chat toolbar beside it, which
            # reads Clear then Copy. That order is Gradio's: `buttons` accepts only
            # "share"/"copy"/"copy_all" or custom buttons, and the Clear it renders
            # ahead of them is not in that list and cannot be moved. Two toolbars a
            # few hundred pixels apart disagreeing about where "delete" lives is the
            # kind of thing a visitor notices, so the one we control follows the one
            # we do not.
            with gr.Row(visible=False, elem_id="report-actions") as report_actions:
                trash_button = gr.Button("", icon=str(ICONS / "trash.svg"), size="sm")
                # elem_id because COPY_JS has to find THIS button's icon to swap it
                # for a checkmark. It used to select the first button in the row,
                # which was this one until the row was reordered to match Gradio's
                # chat toolbar — after which clicking copy put the checkmark on the
                # delete button. Position is not identity.
                copy_button = gr.Button("", icon=str(ICONS / "copy.svg"), size="sm",
                                        elem_id="copy-report")
                download_button = gr.DownloadButton("", icon=str(ICONS / "download.svg"), size="sm")
            # gr.HTML, not gr.Markdown: the panel renders report_html.py's markup,
            # and Markdown would put it through DOMPurify with a config this repo
            # cannot read. Escaping every interpolated value in one module is a
            # boundary that can be tested; guessing an allow-list is not.
            report_output = gr.HTML("", elem_classes="report-panel")

    outs = [chatbot, message_box, report_output, report_state,
            context_line, scanned_source, stop_button, report_col, download_button,
            report_actions]
    submit_event = message_box.submit(
        respond, inputs=[message_box, chatbot, report_state, scanned_source], outputs=outs,
        show_progress="hidden",
    )
    stop_button.click(
        on_stop, inputs=[chatbot],
        outputs=[chatbot, message_box, report_output, report_col, stop_button,
                 report_actions],
        cancels=[submit_event],
    )
    trash_button.click(
        on_trash,
        outputs=[report_output, report_state, context_line,
                 scanned_source, report_col, report_actions],
        show_progress="hidden",
        js=TRASH_JS,
    )
    # No inputs: COPY_JS reads the markdown straight out of the DOM. See its comment.
    copy_button.click(None, js=COPY_JS)
    # Client-side setup: focus the input, and make the example chips submit. A load
    # event is the only place this runs under Gradio 6 — see UI_STYLE above.
    demo.load(None, js=EXAMPLES_JS)
    demo.load(None, js=COMPOSER_JS)

# Public-hosting guardrails: a bounded waiting room instead of an unbounded
# queue, and a few concurrent turns so one long scan doesn't serialize everyone.
# Named rather than inlined because scripts/measure_concurrency.py does the
# admission arithmetic from them — it used to restate the two numbers in its own
# source, which would have gone stale the moment either changed here.
QUEUE_MAX_SIZE = 16
QUEUE_CONCURRENCY = 4
demo.queue(max_size=QUEUE_MAX_SIZE, default_concurrency_limit=QUEUE_CONCURRENCY)

# The outer half of the size bound, and the only half that acts on BYTES.
#
# scan.MAX_DOCUMENT_CHARS is the one that matters for spend, but it can only fire
# after read_document has parsed the upload — and parsing is itself the memory event
# worth avoiding: pypdf holds the whole file, and this deployment is one instance
# whose measured peak across four concurrent scans is ~300 MB. Gradio's default here
# is None, i.e. unlimited, so without this line a large enough upload is an OOM before
# any of the reasoning in scan.py gets a turn.
#
# Looser than the character limit on purpose: these bound different things. A PDF that
# is mostly scanned images carries few characters per megabyte, and that document has
# earned the "no text layer" answer it already gets rather than a size error.
#
# But not much looser, and the deployment is why. The service runs on 1 GiB with
# `--max-instances 1` and Cloud Run's own `containerConcurrency` at 80 — which is not
# the 4 that Gradio's queue enforces, because the queue governs event handlers and an
# upload arrives before any handler runs. Cloud Run also has no disk: bytes written to
# the filesystem are charged to the same 1 GiB. So the stress case is concurrent
# uploads, not concurrent scans, and this keeps even an absurd 80 of them under the
# limit alongside the ~300 MB the app already occupies.
#
# Gradio wants a string or an int; the int from upload.py is the one source of truth,
# and api.py reads the same constant so the two surfaces cannot drift apart.
MAX_UPLOAD_SIZE = MAX_UPLOAD_BYTES

# Gradio hard-codes its own Open Graph tags into the page it serves, so the link
# preview on LinkedIn, Slack or a recruiter's inbox reads "Gradio — Click to try out
# the app!" under someone else's Twitter handle, and og:url ships as the literal
# unsubstituted string "{url}". The favicon was the visible half of this; the share
# card is the half that reaches people who never click. Rewritten on the way out
# because the tags are baked into Gradio's template, not configurable.
DEMO_URL = "https://leasehound-671004460975.us-west1.run.app"
# A purpose-built 1200x630 card, not the README still: every platform crops share
# images to about 1.91:1, and the screenshot is 1.42:1, so a quarter of its height
# was cut — and at card size its UI text was unreadable anyway. Regenerate with
# scripts/make_og.py, which reads the two strings below so the card cannot drift
# from these tags. Served from the public repo so a scraper can reach it.
SHARE_CARD = "docs/og.png"
# SOCIAL_TITLE is defined above, beside gr.Blocks, because the tab wears it too.
SOCIAL_DESCRIPTION = ("Scan a Washington lease for clauses that are void under "
                      "RCW 59.18 — every verdict cites the statute.")
# Card only, never in the meta description. The description is read by whoever gets
# the link and should say what the thing does; the card is read by people scanning
# for what it is built out of. Both audiences are real and want different sentences.
SOCIAL_STACK = "Two-layer RAG over Washington tenant law"
# The card shows one real finding. The clause text is read out of the sample lease
# rather than retyped — an invented quotation on a card about citing sources would be
# the one mistake this project cannot afford. The section is the verdict a real scan
# of that lease returns; it is the pairing recorded in docs/screenshot.png.
CARD_CLAUSE_HEADING = "3. LATE CHARGES."
CARD_CITATION = "RCW 59.18.170 — no late fee before the fifth day"
# The verdict counts the report shows for that lease. Not derived, and the reason
# is worth recording: evaluation/scan_results.json has `flagged_yellow`, but that
# field means "planted violations that came back yellow" — a different quantity
# from "cautions in the report", which lands in `cautions` (eval_scan.py:123) and
# is written out as `unplanted_yellows`. That field was added after the stored
# artifact was generated, so the artifact cannot supply this count today. The
# clear count is not arithmetic either: 7+1+7 exceeds the numbered lines in the
# lease, because the scanner's clause splitting is not a regex over "N.".
# These are what the live app returns, the same run recorded in docs/screenshot.png.
# Re-derive from `unplanted_yellows` the next time the scan eval is re-run.
CARD_VERDICTS = "7 red flags | 1 caution | 2 missing protections | 7 clear"
# Matched by attribute rather than by exact string: Gradio emits these twice, in two
# blocks, and wraps some of them across lines, so a literal replacement caught the
# titles and left og:image pointing at Gradio's own banner. An empty value here means
# drop the tag — shipping someone else's URL is worse than shipping none.
def share_card_url() -> str:
    """The card's URL with a content hash on it, the way Next.js versions its own.

    Without the hash the URL never changes, and LinkedIn caches share images BY URL:
    a regenerated card kept showing the previous one, and Post Inspector did not fix
    it — that re-fetches the page, not an image it believes it already has. Same
    reason `docs/og.png` regenerating is not enough on its own.

    Falls back to the bare path if the file is missing, because a share tag is not
    worth failing a boot over: the image 404s and the page still serves.
    """
    base = f"https://raw.githubusercontent.com/tywangq/leasehound/main/{SHARE_CARD}"
    card = REPO_ROOT / SHARE_CARD
    if not card.is_file():
        return base
    digest = hashlib.sha256(card.read_bytes()).hexdigest()[:16]
    return f"{base}?v={digest}"


SHARE_CARD_URL = share_card_url()

SOCIAL_CONTENT = {
    "og:title": SOCIAL_TITLE,
    "twitter:title": SOCIAL_TITLE,
    "og:description": SOCIAL_DESCRIPTION,
    "twitter:description": SOCIAL_DESCRIPTION,
    "og:url": DEMO_URL,
    "og:image": SHARE_CARD_URL,
    "twitter:image": SHARE_CARD_URL,
    "twitter:creator": "",
    "twitter:site": "",
}
META_TAG_RE = re.compile(r'<meta\s[^>]*?(property|name)="([\w:]+)"[^>]*?/>', re.S)


def rebrand_meta_tag(match: re.Match) -> str:
    attribute, key = match.group(1), match.group(2)
    if key not in SOCIAL_CONTENT:
        return match.group(0)
    value = SOCIAL_CONTENT[key]
    return f'<meta {attribute}="{key}" content="{value}" />' if value else ""


async def rebrand_social_preview(request, call_next):
    """Swap Gradio's share-card metadata for this app's, on HTML responses only."""
    response = await call_next(request)
    if not response.headers.get("content-type", "").startswith("text/html"):
        return response
    body = b"".join([chunk async for chunk in response.body_iterator])
    text = META_TAG_RE.sub(rebrand_meta_tag, body.decode("utf-8", "replace"))
    # Declared rather than left to the browser's default /favicon.ico probe, so the
    # tab icon does not depend on a fallback. PNG, not SVG: this shipped as an SVG
    # holding the emoji as `<text>`, served a correct 200 image/svg+xml, and showed
    # nothing — Safari does not support SVG favicons at all, and a text glyph needs
    # an emoji font resolved inside the favicon's rendering context. See
    # scripts/render_favicon.py, which draws the real glyph in a real browser.
    text = text.replace("<head>", '<head>\n\t\t<link rel="icon" type="image/png" '
                                  'href="/favicon.ico" />', 1)
    headers = {k: v for k, v in response.headers.items() if k.lower() != "content-length"}
    return Response(content=text, status_code=response.status_code,
                    headers=headers, media_type="text/html")


def serve() -> None:
    """One process, two surfaces: the UI at / and the HTTP API at /v1.

    Mounted rather than launched, so `python -m leasehound.app` stays the single
    serving command — the container's CMD, the README, and .claude/launch.json all
    keep working, and there is no second entry point to remember which of the two
    a given environment runs. The env vars are Gradio's own names because that is
    what the Dockerfile already sets.
    """
    import uvicorn

    from leasehound.api import api

    server = gr.mount_gradio_app(api, demo, path="/",
                                 favicon_path=str(ICONS / "favicon.png"),
                                 max_file_size=MAX_UPLOAD_SIZE, **UI_STYLE)
    server.middleware("http")(rebrand_social_preview)
    uvicorn.run(
        server,
        host=os.environ.get("GRADIO_SERVER_NAME", "127.0.0.1"),
        port=int(os.environ.get("GRADIO_SERVER_PORT", "7860")),
    )


if __name__ == "__main__":
    serve()
