"""Gradio demo UI — one chat, artifact-style report panel.

A single multimodal input drives everything: attach a lease (or click the
sample-lease example) to scan it; just type to ask questions. Scan progress
streams into the chat clause by clause; the finished report pins to the
right-hand panel so it stays visible while you chat about it. The chat's
context is explicit — Washington law always, plus the latest scan report once
a scan has run.

Privacy: uploads are parsed in memory and the temp file is deleted right after
parsing; clause text goes to the OpenAI API for analysis and is never written
to disk. Finished scans are cached in process memory, keyed by document
content hash, so rescanning an identical document costs zero API calls.

Usage:
    python -m leasehound.app     # http://localhost:7860
"""

import hashlib
import os
import re
import shutil
import tempfile
import threading
import time
import traceback
from collections import OrderedDict
from html import escape
from pathlib import Path

import gradio as gr
from starlette.responses import Response

from leasehound.answer import (
    MAX_HISTORY_MESSAGE_CHARS,
    QuestionTooLong,
    answer_question,
)
from leasehound.jurisdiction import jurisdiction_mismatch
from leasehound.metrics import UsageMeter, log_scan
from leasehound.report_html import render_report_html
from leasehound.scan import (
    MAX_CLAUSES,
    DocumentTooLarge,
    NoTextExtracted,
    ScanResult,
    count_verdicts,
    render_report,
    scan_steps,
)
from leasehound.upload import MAX_UPLOAD_BYTES, read_document

REPO_ROOT = Path(__file__).parent.parent
SAMPLE_LEASE = REPO_ROOT / "examples" / "sample_lease.md"
# The hosted demo serves one jurisdiction. Named once: the scan and the report used
# to be handed the string "wa" separately, and the scan path took it as a default
# argument while this file hard-coded it, so they could disagree silently.
DEMO_STATE = "wa"
ICONS = Path(__file__).parent / "assets"

HERO = """
<div class="hero">
  <div class="wordmark">🐕 LeaseHound</div>
  <p class="tagline">Sniffs out the clauses that shouldn't be there.</p>
</div>
"""

CSS = """
.gradio-container {max-width: 1200px !important; margin: 0 auto !important;}
.hero {text-align: center; padding: 28px 0 8px;}
.hero .wordmark {font-size: 2.4em; font-weight: 700; letter-spacing: -0.5px;}
.hero .tagline {font-size: 1.25em; margin: 6px 0 4px;}
.step-sub {font-size: 0.9em; opacity: 0.75;}
.main-row {justify-content: center; align-items: stretch;}
/* The report panel. Styled to match the share card at docs/og.png, which is
   generated by scripts/make_og.py from the same report — a card that looks more
   finished than the product it links to is a downgrade on arrival.
   Every class here is emitted by report_html.py; nothing depends on Markdown's
   generated structure, which is what the old h1/h2 rules were doing. */
.report-panel {--lh-red: #dc2626; --lh-amber: #d97706; --lh-teal: #0d9488;
               --lh-green: #16a34a; --lh-ink: #0f172a; --lh-body: #334155;
               --lh-muted: #94a3b8; --lh-hair: #e2e8f0;}
.report-panel .lh-md {display: none;}
.report-panel .lh-title {font-size: 1.3em; font-weight: 700; color: var(--lh-ink);
                         margin: 2px 0 4px;}
.report-panel .lh-meta {font-size: 0.88em; color: var(--lh-muted); margin: 0 0 14px;}
.report-panel .lh-meta code {font-size: 0.95em; background: none; padding: 0;}
.report-panel .lh-dot {margin: 0 7px;}
/* Verdict counts as chips, the one thing a Markdown string could not carry: the
   summary used to be one bold run with "·" between the numbers, and four emoji
   doing the colour coding — 🚩⚠️🔍✅ is four visual weights and four metaphors in
   a row, rendered differently on every platform. The dot is drawn now. */
.report-panel .lh-chips {display: flex; flex-wrap: wrap; gap: 8px; margin: 0 0 16px;}
.report-panel .lh-chip {display: inline-flex; align-items: center; gap: 8px;
                        font-size: 0.86em; font-weight: 600; color: var(--lh-body);
                        padding: 5px 13px; border: 1px solid var(--lh-hair);
                        border-radius: 999px; white-space: nowrap;}
.report-panel .lh-chip i {width: 9px; height: 9px; border-radius: 2px; flex: none;}
.report-panel .lh-red i {background: var(--lh-red);}
.report-panel .lh-yellow i {background: var(--lh-amber);}
.report-panel .lh-missing i {background: var(--lh-teal);}
.report-panel .lh-green i {background: var(--lh-green);}
.report-panel .lh-note {font-size: 0.86em; color: var(--lh-body); line-height: 1.5;
                        margin: 0 0 12px; padding: 9px 13px; border-radius: 8px;
                        background: #f8fafc; border-left: 3px solid var(--lh-hair);}
.report-panel .lh-note-jurisdiction, .report-panel .lh-note-gate,
.report-panel .lh-note-partial {background: #fffbeb; border-left-color: var(--lh-amber);}
.report-panel .lh-section {font-size: 0.78em; font-weight: 700; letter-spacing: 0.08em;
                           text-transform: uppercase; margin: 22px 0 10px;}
.report-panel h2.lh-red {color: var(--lh-red);}
.report-panel h2.lh-yellow {color: var(--lh-amber);}
.report-panel h2.lh-missing {color: var(--lh-teal);}
/* One finding, one bordered block with a coloured rail. Findings used to run
   together as heading + paragraph + list, so which explanation belonged to which
   clause was a matter of reading order. */
.report-panel .lh-finding {position: relative; margin: 0 0 12px; padding: 14px 16px 14px 20px;
                           border: 1px solid var(--lh-hair); border-radius: 10px;
                           background: #fff; overflow: hidden;}
.report-panel .lh-finding::before {content: ""; position: absolute; left: 0; top: 0;
                                   bottom: 0; width: 4px;}
.report-panel .lh-finding.lh-red::before {background: var(--lh-red);}
.report-panel .lh-finding.lh-yellow::before {background: var(--lh-amber);}
.report-panel .lh-finding.lh-red {background: #fffbfb; border-color: #f4d4d4;}
.report-panel .lh-finding-head {font-size: 0.74em; font-weight: 700; letter-spacing: 0.07em;
                                text-transform: uppercase; color: var(--lh-muted);
                                margin: 0 0 7px;}
/* Serif for the quoted clause, sans for everything said about it: the lease's words
   and the tool's words were the same face at the same weight, and the reader had to
   work out which was which. */
.report-panel .lh-clause {font-family: Georgia, "Times New Roman", serif;
                          font-size: 1.03em; line-height: 1.45; color: var(--lh-ink);
                          margin: 0 0 10px; padding: 0; border: none; background: none;}
.report-panel .lh-explain {font-size: 0.92em; line-height: 1.55; color: var(--lh-body);
                           margin: 0;}
.report-panel .lh-cites {display: flex; flex-wrap: wrap; gap: 8px; margin: 10px 0 0;}
.report-panel .lh-cite {font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
                        font-size: 0.82em; color: #0f766e; text-decoration: none;
                        border-bottom: 1px solid rgba(15, 118, 110, 0.3);}
.report-panel a.lh-cite:hover {border-bottom-color: #0f766e;}
.report-panel .lh-missing-list {margin: 0; padding-left: 20px; font-size: 0.9em;
                                line-height: 1.6; color: var(--lh-body);}
.report-panel .lh-tail {font-size: 0.86em; color: var(--lh-muted); margin: 16px 0 0;}
.report-panel .lh-waiting {font-size: 0.92em; color: var(--lh-muted);}
.report-panel .lh-notjudged {color: var(--lh-amber);}
@media (prefers-color-scheme: dark) {
  .report-panel {--lh-ink: #e6edf3; --lh-body: #c3ccd6; --lh-muted: #7d8b99;
                 --lh-hair: #263139;}
  .report-panel .lh-finding {background: #11181f; border-color: #263139;}
  .report-panel .lh-finding.lh-red {background: #1b1315; border-color: #4a2226;}
  .report-panel .lh-note {background: #11181f;}
  .report-panel .lh-note-jurisdiction, .report-panel .lh-note-gate,
  .report-panel .lh-note-partial {background: #1d1710;}
  .report-panel .lh-cite {color: #2dd4bf; border-bottom-color: rgba(45, 212, 191, 0.3);}
}
/* The [copy][download][trash] row pins to the column's top-right corner and
   stays put while the report scrolls underneath. */
.report-col {position: relative;}
#report-actions {position: absolute; top: 6px; right: 6px; z-index: 10;
                 width: auto; min-width: 0; gap: 6px; flex-wrap: nowrap;}
/* Icon-only buttons: gradio gives button imgs max-width:100%, which resolves
   against the empty label's collapsed content box and squashes the icon to 0. */
#report-actions button {width: auto; min-width: 30px; flex-grow: 0; padding: 4px 8px;}
#report-actions button img {width: 13px; height: 13px; margin: 0;
                            max-width: none; flex-shrink: 0;}
/* Desktop layout. Both columns get explicit widths (flex-grow stays 0) so the
   solo ↔ split switch is a deterministic slide: animating flex-grow instead
   makes widths depend on the grow *ratio*, which overshoots — the chat column
   balloons to full row width the instant its sibling leaves the DOM, then
   shrinks back. flex-basis is not !important so the entry keyframe can drive
   it (CSS animations lose to !important declarations). */
@media (min-width: 901px) {
  .chat-col {transition: flex-basis 0.45s ease;}
  .main-row:not(:has(.report-col)) .chat-col {flex-grow: 0 !important; flex-basis: 760px; max-width: 760px;}
  .main-row:has(.report-col) .chat-col {flex-grow: 0 !important; flex-basis: calc(50% - (var(--layout-gap, 8px) / 2));}
  /* Side-by-side, the report column stretches to the chat column's height and
     the report scrolls inside it, so both columns end flush. */
  .report-col {display: flex !important; flex-direction: column;
               flex-grow: 0 !important;
               flex-basis: calc(50% - (var(--layout-gap, 8px) / 2));
               min-width: 0 !important; overflow: hidden;
               transition: flex-basis 0.45s ease, opacity 0.45s ease;
               animation: report-in 0.45s ease;}
  @keyframes report-in {from {flex-basis: 0px; opacity: 0;}}
  /* overflow-y needs !important and the rest of this rule does not, which is worth
     writing down. As a gr.Markdown the panel took this rule as written. As a gr.HTML
     it also carries Gradio's `hide-contain`, which sets overflow and wins — so `flex`
     and `min-height` still landed while `overflow-y` silently did not, and a long
     report was CLIPPED at the column's height. Nothing looked broken: the panel
     rendered, the wheel scrolled the page past it, and the findings below the fold
     were simply unreachable. Narrow screens use their own rule below and never were.
     Measured rather than guessed — computed overflow-y read `visible` on the live
     page, while flex and min-height read as written. */
  .report-panel {flex: 1 1 0; min-height: 0; overflow-y: auto !important; padding: 0 4px;}
  /* Trash: TRASH_JS adds .closing so both columns slide to their solo
     positions *before* the server removes the report column from the DOM
     (on_trash sleeps past the transition). Must come after the :has rules —
     same specificity, so source order decides. */
  .main-row.closing .chat-col {flex-basis: 760px;}
  .main-row.closing .report-col {flex-basis: 0px; opacity: 0;}
}
@media (max-width: 900px) {
  .report-panel {max-height: 65vh; overflow-y: auto; padding: 0 4px;}
}
/* STRETCH, not center. This rule said `center` and was written when gradio 5 laid
   the container out as a ROW, where centering the cross axis meant centering the
   icons and the textarea vertically. Gradio 6 makes the container a COLUMN, so the
   same declaration centers the cross axis HORIZONTALLY: the input wrapper collapsed
   to its content and the composer went from 734px wide to 237px, wrapping the
   placeholder onto two lines and clipping "Washington…" off the end. Nothing caught
   it — the tests render no CSS, and the README screenshot that would have shown it
   predated the upgrade. The vertical centering it used to do is now the textarea's
   own align-content, below. */
.chat-col .multimodal-textbox .input-container {align-items: stretch !important;}
.chat-col .multimodal-textbox textarea {align-content: center;}
/* Attached-file chip: gradio's 48px thumbnail dwarfs the 30px attach/send
   icons beside it. Direct-child only, so the delete ✕ keeps its own size. */
.chat-col .multimodal-textbox .thumbnail-item {width: 30px !important; height: 30px !important;}
.chat-col .multimodal-textbox .thumbnail-item > :is(svg, img) {width: 16px !important; height: 16px !important;}
#example-scan button, #example-prompts button {text-align: left !important; justify-content: flex-start !important;}
/* The scan example renders its example_labels string in a bare div (14px by
   default); match the question examples' markdown <p> size. */
#example-scan .gallery-item {font-size: var(--text-lg, 16px);}
@media (max-width: 900px) {
  .main-row {flex-direction: column !important;}
  .main-row .chat-col {flex-grow: 1 !important; flex-basis: auto !important; max-width: 100% !important;}
}
footer {visibility: hidden;}
"""

LAW_ONLY_CONTEXT = (
    "🧠 The hound knows **Washington tenant law (RCW 59.18)**. "
    "Scan a lease and it will know your report too."
)
ALREADY_SNIFFED = "🐕 Already sniffed this one — the report is still on the right."
# Everything before the first verdict: reading the document, splitting it, and the
# gate call. The pair to ask mode's "🐕 Thinking…", and short for the same reason —
# it is on screen for about a second, and a sentence nobody can finish reading before
# it is replaced is worse than no sentence. The first draft explained what the gate
# was doing and how the refusal worked, which was true, unreadable, and immediately
# followed by the refusal it was explaining.
#
# What it must NOT say is anything about clauses. For that second the UI used to show
# "0/N clauses sniffed" beside an opening report panel, so a document about to be
# refused had already been announced as a scan in progress and the refusal read as
# the app changing its mind. Nothing is claimed about the clauses until the gate has
# answered, and the panel does not open until the first verdict.
SNIFF_STARTING = "🐕 Sniffing…"
CACHED_SNIFF = (
    "🐕 The hound has sniffed this exact lease before — here's the saved report, "
    "no fresh API calls. Attach a different lease to watch a live scan."
)
CALLED_OFF = "🐕 Called off — the hound stopped mid-sniff. Scan again whenever you're ready."
NOTHING_EXTRACTED = (
    "🐕 The hound couldn't find any text in this document — a scanned or photo PDF has "
    "no text layer. Try a text-based .pdf, .md, or .txt."
)
# The override the refusal below asks for. A phrase rather than a button because the
# upload is deleted as soon as its text is read (see cleanup_upload), so the document
# has to come back with the request — and a phrase the visitor types is unambiguously
# the visitor's, which is the property that keeps a planted "this is not a lease" line
# from suppressing anything on its own.
SCAN_ANYWAY_PHRASE = "scan anyway"

# Reaches the screen for two different documents — a guide about renting, and an
# `other` the reader insisted on — so it must not name either. Saying "a document
# about renting" here put that sentence above a scan of a banana bread recipe.
NOT_A_LEASE = (
    "🐕 The hound gave this a good sniff and it doesn't smell like a residential "
    "lease. Sniffing it anyway — but landlord-tenant verdicts on something that isn't "
    "a lease are unreliable, so read the report with that in mind."
)
# The refusal half. Says what it would take for a scan to mean anything, and points
# at the button — because the old warning claimed the scan happened "on request"
# when there was no way to make one.
NOT_ABOUT_RENTING = (
    "🛑 The hound had a good sniff and this doesn't smell like a lease **or** like "
    "anything about renting — no parties, no dwelling, no rent, no obligations. "
    "Judging it against landlord-tenant law would fill a page with confident "
    "nonsense, so nothing was judged and nothing was spent past the first look.\n\n"
    f"If it really is a lease, attach it again with **{SCAN_ANYWAY_PHRASE}** in the "
    "message. It has to be re-attached because your upload is deleted the moment its "
    "text is read — the hound doesn't keep a copy waiting for a second opinion."
)
# A different failure from NOT_A_LEASE, and it needs its own words: this document IS
# a residential lease, the gate is right to accept it, and what is wrong is the law
# being applied to it. Both directions of wrongness are spelled out because only one
# is intuitive — a reader expects "we may have missed something", not "the clause we
# flagged is fine where you live".
WRONG_STATE = (
    "🌎 This lease points to **{document} law**, and the hound only knows "
    "**Washington** (RCW 59.18). It'll finish the scan, but every section it cites "
    "will be a Washington statute that doesn't govern a {document} tenancy — so a red "
    "flag below may be perfectly enforceable where this lease actually lives, and a "
    "clause the hound calls clear may be void there with nothing in the report to say "
    "so. Read it as a Washington-shaped guess, not as a verdict on your rights."
)
# The ask-mode half of WRONG_STATE. Shorter, because there is no report to qualify —
# only the one answer that is about to arrive — and it has to name the consequence
# rather than the mechanism: a renter does not care which corpus is loaded, they care
# that the sentence they are about to read is about somebody else's state.
WRONG_STATE_QUESTION = (
    "🌎 You mentioned **{asked}**, and the hound only knows **Washington** law "
    "(RCW 59.18). Here's the Washington answer — but {asked} has its own landlord-"
    "tenant statutes, and on this question they may well say something different. "
    "Worth checking with a tenant-rights service where you actually rent."
)
PARTIAL_SCAN = (
    "🐕 This document splits into {count} clauses — long-form agreements really do run "
    "this long. The hound judges the first {limit}, so clauses {rest} won't get a verdict; "
    "the report says so too. The missing-protections check still reads the whole thing. "
    "Attach just the part you care about for full coverage."
)
# The other end of the same size question, and the one that has an answer instead of a
# degraded scan: see scan.DocumentTooLarge for why this is refused where the clause cap
# only trims. Phrased in pages because nobody uploading a lease thinks in characters.
TOO_LARGE = (
    "🐕 That file is too big for one scan — about {pages} pages of text, and the hound "
    "reads up to roughly {limit}. Nothing was scanned and nothing was spent. A residential "
    "lease is almost never this long, so this is usually a whole document bundle: attach "
    "just the lease or the section you care about."
)
# Measured, not guessed — the first draft of this line said 1800 and was wrong by most
# of a page. Across the five real published leases in eval_real_formats.py the extracted
# text runs 2,666–5,820 characters per PDF page (median 3,130); the outlier is the HUD
# addendum, whose 5 pages are unusually dense. 3000 puts the limit at ~128 pages.
#
# The copy says "about" and this stays a round number on purpose: the job is to give a
# visitor a sense of scale, not a figure they could hold the scan to.
CHARS_PER_PAGE = 3000

# The ask side of the same size question. A question is not a file, which is exactly why
# it went unbounded: the four spend bounds in the README were all about scans, and the
# one route that did cap a question — /v1/ask, at the same 2,000 characters — is the one
# that returns 503 on the hosted demo. Characters here, not pages: somebody who pastes
# this much into a chat box knows they pasted a lot.
QUESTION_TOO_LONG = (
    "🐕 That's a lot to read in one go — {chars} characters, and the hound takes up to "
    "{limit} per question. Nothing was spent. Ask about one clause or one situation at a "
    "time and the answers get sharper anyway; if it's a whole document, attach it with "
    "the paperclip and let the hound scan it instead."
)
# How much of a scan report rides along in ask mode's context. Imported by nothing else
# here on purpose: it IS answer.MAX_HISTORY_MESSAGE_CHARS, because the report is the
# largest message this pipeline legitimately produces and there is no second opinion to
# have about it. Before, this was a bare 6000 in answer_flow while /v1/ask accepted
# 200,000 — the same context under two limits 33x apart, neither derived from the other.
REPORT_CONTEXT_CHARS = MAX_HISTORY_MESSAGE_CHARS


def in_pages(chars: int) -> str:
    return f"{max(1, round(chars / CHARS_PER_PAGE)):,}"
HOUND_TRIPPED = (
    "🐕 The hound tripped over an error and lost the scent — nothing was changed. "
    "Try again, or try a different file."
)
# The example chip shows the file name; once clicked, the file rides along as an
# attachment, so the message itself drops the "(sample_lease.md)" suffix.
SCAN_EXAMPLE = {
    "text": "Sniff this sample lease for red flags",
    "files": [str(SAMPLE_LEASE)],
}
SCAN_EXAMPLE_LABEL = "Sniff this sample lease for red flags (sample_lease.md)"
QUESTION_EXAMPLES = [
    {"text": "Can my landlord charge a late fee if rent is 3 days late?", "files": []},
    {"text": "How much notice before my landlord can enter?", "files": []},
    {"text": "When do I get my security deposit back after moving out?", "files": []},
]


def report_context(name: str) -> str:
    return f"🧠 The hound knows **Washington tenant law** + the **scan report of `{name}`**."


# No --- divider: markdown gives an <hr> generous margins on top of the
# paragraph gap, which reads as a hole between the answer and its sources.
# "Statutes cited:" — right under the answer, "in this answer" says nothing.
FOOTER_MARK = "\n\n**Statutes cited:**"
# A model-written imitation of the footer (any trailing "Statutes cited …"
# block, however formatted or worded) — stripped before the real one is appended.
MODEL_FOOTER = re.compile(
    r"\n+(?:-{3,}\n+)?\**Statutes cited(?: in this answer)?:?\**[\s\S]*\Z"
)


def sources_footer(answer: str, chunks) -> str:
    """List only the statutes the answer actually cites, not everything retrieved.

    An off-topic question still retrieves (irrelevant) chunks, and the answer
    honestly declines — the footer shouldn't then present those chunks as
    sources. Cited = mentioned in the answer AND present in the retrieved set.
    """
    url_by_section = {}
    for chunk in chunks:
        section = chunk.metadata.get("section")
        if section:
            url_by_section.setdefault(section, chunk.metadata.get("url", ""))
    seen, lines = set(), []
    for section in re.findall(r"RCW \d+\.\d+\.\d+", answer):
        if section in url_by_section and section not in seen:
            seen.add(section)
            url = url_by_section[section]
            lines.append(f"- [{section}]({url})" if url else f"- {section}")
    return FOOTER_MARK + "\n" + "\n".join(lines) if lines else ""


def strip_footer(message: dict) -> dict:
    """Drop the sources footer from an assistant message before it re-enters the LLM.

    The footer is display chrome. Fed back as conversation history, the model
    learns the pattern and writes its own copy at the end of the next answer —
    which then gets the real footer appended below it, doubling the block.
    """
    content = message.get("content")
    if message.get("role") == "assistant" and isinstance(content, str) and FOOTER_MARK in content:
        return {**message, "content": content.split(FOOTER_MARK)[0].rstrip()}
    return message


def cleanup_upload(path: Path) -> None:
    """Delete an uploaded temp file as soon as its text is extracted (privacy)."""
    if path != SAMPLE_LEASE and str(path).startswith(tempfile.gettempdir()):
        path.unlink(missing_ok=True)


# Cross-visitor scan cache, keyed by document CONTENT — not upload path, which
# is unique per upload, and not session, which is one browser tab. Most demo
# traffic scans the one sample lease; only its first scan after a cold start
# should cost API calls. Memory only (never disk), bounded, gone with the
# instance — the next first scan re-warms it. Stores findings + protections
# rather than the rendered report so a hit renders under its own file name.
CACHE_MAX_ENTRIES = 32
_scan_cache: OrderedDict[str, dict] = OrderedDict()
_scan_cache_lock = threading.Lock()


def cache_key(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", "replace")).hexdigest()


def cache_get(digest: str) -> dict | None:
    with _scan_cache_lock:
        entry = _scan_cache.get(digest)
        if entry is not None:
            _scan_cache.move_to_end(digest)
        return entry


def cache_put(digest: str, entry: dict) -> None:
    with _scan_cache_lock:
        _scan_cache[digest] = entry
        _scan_cache.move_to_end(digest)
        while len(_scan_cache) > CACHE_MAX_ENTRIES:
            _scan_cache.popitem(last=False)


def progress_line(done: int, total: int) -> str:
    return f"🐕 On the scent — {done}/{total} clauses sniffed…"


# The one thing in this app that really does write lease-derived content to disk — the
# report quotes the clauses it judged — and it has to, because a download button can only
# serve a file. What it must not do is keep them: this made a fresh temp directory per
# finished scan and deleted none of them, so a long-lived instance accumulated every
# report it had ever rendered. On Cloud Run that is not a disk, it is a slice of the same
# 1 GiB the scan is running in.
#
# A subdirectory per report rather than one directory of files, because the file NAME is
# the visitor's own and two visitors uploading `lease.pdf` must not be able to hand each
# other a report. Pruning is oldest-first and generous enough that a download stays valid
# far longer than anyone waits before clicking: 32 more scans have to finish first, the
# same bound and the same reasoning as the scan cache above.
REPORTS_ROOT = Path(tempfile.mkdtemp(prefix="leasehound_reports_"))
MAX_REPORT_FILES = CACHE_MAX_ENTRIES
_report_lock = threading.Lock()


def report_file(report: str, source_name: str) -> str:
    """Write the report where the download button can serve it, and prune the rest."""
    with _report_lock:
        REPORTS_ROOT.mkdir(parents=True, exist_ok=True)
        folder = Path(tempfile.mkdtemp(dir=REPORTS_ROOT))
        path = folder / f"scan_report_{Path(source_name).stem}.md"
        path.write_text(report, encoding="utf-8")
        stale = sorted(REPORTS_ROOT.iterdir(), key=lambda d: d.stat().st_mtime)
        for folder_to_drop in stale[:-MAX_REPORT_FILES]:
            shutil.rmtree(folder_to_drop, ignore_errors=True)
    return str(path)


# Every event yields the same 10 outputs. `col` shows/hides the report column, so
# the page is a single centered chat until there is something to pin. The input
# box is disabled while a scan runs — a submit queued mid-scan would carry a
# pre-scan snapshot of the cache state and silently rescan. `actions` is the
# [copy][download][trash] row: one switch so the three buttons always appear
# together, only once a finished report is pinned. `download` carries the file.
# [chatbot, message_box, report_output, report_state, context_line,
#  scanned_source, stop_button, report_col, download_button, report_actions]


def _out(history=gr.skip(), box=gr.skip(), report=gr.skip(), state=gr.skip(),
         context=gr.skip(), source=gr.skip(), stop=gr.skip(), col=gr.skip(),
         download=gr.skip(), actions=gr.skip()):
    return history, box, report, state, context, source, stop, col, download, actions


def answer_flow(question, history, report, context_base):
    """Append the hound's answer to an already-appended user message."""
    history.append({"role": "assistant", "content": "🐕 Thinking…"})
    yield _out(history)
    # Trim BEFORE prepending, so the report survives; strip footers so the
    # model doesn't mimic them (see strip_footer).
    #
    # `[-10:]` bounds how many messages the model sees and nothing about how big they
    # are, which is the same sentence as MAX_CLAUSES bounding the clause count and
    # nothing about the document. The size bound lives in answer_question, because
    # this handler is not the only door — Gradio publishes it as an unauthenticated
    # HTTP endpoint, and `history` is then whatever the caller sends.
    context_history = [strip_footer(m) for m in list(context_base)[-10:]]
    if report:
        context_history = [
            {
                "role": "user",
                "content": ("For context, here is the scan report of my lease:\n\n"
                            + report[:REPORT_CONTEXT_CHARS]),
            },
            {
                "role": "assistant",
                "content": "Got it — I'll answer your questions with your scan report in mind.",
            },
        ] + context_history
    try:
        answered = answer_question(question, context_history, report_context=bool(report))
    except QuestionTooLong as long_question:
        # Refused, not truncated: answering half a question answers a different
        # question. Costs $0 — the check runs ahead of the router, which is ask mode's
        # first API call.
        history[-1]["content"] = QUESTION_TOO_LONG.format(
            chars=f"{long_question.chars:,}", limit=f"{long_question.limit:,}")
        yield _out(history, box=gr.update(interactive=True))
        return
    # `routed` guards it: the warning is about the ANSWER being Washington law, and the
    # chitchat path has no legal content to be wrong about. "Hi, I'm in Oregon" would
    # otherwise get a paragraph about which statutes the hound carries in reply to a
    # greeting.
    if answered.routed and jurisdiction_mismatch(answered.jurisdiction, DEMO_STATE):
        # Above the answer, not below it: a renter reading "your landlord cannot do
        # that" has already acted on it by the time they reach a footnote. Inserted
        # rather than replacing "🐕 Thinking…", because the answer is still coming —
        # it is the Washington answer, which is not nothing, it is just not theirs.
        history.insert(-1, {"role": "assistant", "content": WRONG_STATE_QUESTION.format(
            asked=answered.jurisdiction.upper())})
        yield _out(history)
    answer = ""
    for delta in answered.stream:
        answer += delta
        history[-1]["content"] = answer
        yield _out(history)
    answer = MODEL_FOOTER.sub("", answer).rstrip()
    history[-1]["content"] = answer + sources_footer(answer, answered.chunks)
    yield _out(history)


def scan_flow(path, key, history, report, scanned, context_base, question="",
              scan_anyway=False):
    """Scan a lease with per-clause progress in chat; report lands in the side panel."""
    name = path.name
    # `scan_anyway` skips both caches deliberately. Refusals are not cached today,
    # so a miss is what would happen anyway — but an override whose correctness
    # depends on that staying true is one refactor away from silently doing nothing,
    # and "scan anyway" has to mean a scan happened.
    if scanned == key and report and not scan_anyway:
        history.append({"role": "assistant", "content": ALREADY_SNIFFED})
        # `report` here is the stored markdown, and re-rendering HTML would need the
        # findings, which this path does not have. The panel already shows this very
        # report — on_trash clears panel and state together, so they cannot disagree.
        yield _out(history, report=gr.skip(), state=report,
                   context=report_context(name), source=key,
                   stop=gr.update(visible=False), col=gr.update(visible=True),
                   download=gr.update(value=report_file(report, name)),
                   actions=gr.update(visible=True))
        if question:
            yield from answer_flow(question, history, report, context_base)
        return

    text = read_document(path)
    cleanup_upload(path)

    digest = cache_key(text)
    result = cache_get(digest) if not scan_anyway else None
    if result is not None:
        log_scan(UsageMeter(), name, result.clauses_judged,
                 verdicts=count_verdicts(result.findings),
                 missing=missing_protections(result), split_mode=result.split_mode,
                 cache_hit=True, clauses_total=result.clauses_total, client="ui")
        history.append({"role": "assistant", "content": CACHED_SNIFF})
        # The report carries the jurisdiction warning either way, but a cached scan
        # skips every step that narrates one — so the second visitor to attach a
        # California lease saw it only if they opened the panel, while the first was
        # told in chat. Same document, same finding, two different experiences.
        if jurisdiction_mismatch(result.jurisdiction, DEMO_STATE):
            history.append({"role": "assistant", "content": WRONG_STATE.format(
                document=result.jurisdiction.upper())})
        yield from finished_scan(result, name, key, history, context_base, question)
        return

    # Everything below is `scan.scan_steps` narrating itself into chat. The steps —
    # split, gate, each clause, protections — are the pipeline's, not this file's:
    # this function used to re-assemble them from the same primitives the CLI uses,
    # and two copies of a sequence that spends money stay in step only by luck.
    history.append({"role": "assistant", "content": SNIFF_STARTING})
    # A fresh scan makes any previous report stale immediately: law-only context
    # until the new report lands. The panel column stays CLOSED through the gate —
    # opening it here meant a refusal had to close it again a second later.
    yield _out(history, box=gr.update(interactive=False),
               report="", state="", context=LAW_ONLY_CONTEXT, source="",
               stop=gr.update(visible=True), col=gr.update(visible=False),
               actions=gr.update(visible=False))
    try:
        for step in scan_steps(text, name, state=DEMO_STATE, scan_anyway=scan_anyway,
                               client="ui"):
            if step.kind == "judging":
                # The gate has accepted, so this is the first moment a scan may be
                # promised. Over the cap it goes ahead on a prefix — refusing meant a
                # visitor who uploaded a real WA housing agreement (270 clauses) got
                # nothing at all, which is worse than 60 judged clauses that say which
                # 210 they aren't. Keyed off `judging` and not `split` because a long
                # document that was about to be refused used to be told which 60 of its
                # clauses would be judged, and only then told it was not a lease.
                if step.partial:
                    history.insert(-1, {"role": "assistant", "content": PARTIAL_SCAN.format(
                        count=step.total, limit=MAX_CLAUSES,
                        rest=f"{step.judged + 1}–{step.total}")})
                # And the panel opens here rather than on the first verdict, which is
                # what it had to key on before this step existed. 0/N is honest now:
                # it appears only once N clauses are certain to be judged.
                history[-1]["content"] = progress_line(0, step.judged)
                yield _out(history, col=gr.update(visible=True),
                           report=f'<p class="lh-waiting">Sniffing '
                                  f'<code>{escape(name)}</code> — the report will '
                                  f'appear here.</p>')
            elif step.kind == "gate_flagged":
                history.insert(-1, {"role": "assistant", "content": NOT_A_LEASE})
                yield _out(history)
            elif step.kind == "jurisdiction":
                history.insert(-1, {"role": "assistant", "content": WRONG_STATE.format(
                    document=step.document_state.upper())})
                yield _out(history)
            elif step.kind == "gate_refused":
                # Replaces the progress line rather than sitting above it: there is
                # no progress to narrate, and leaving "judging clause 0 of N" on
                # screen would promise a scan that is not going to happen.
                history[-1]["content"] = NOT_ABOUT_RENTING
                yield _out(history)
            elif step.kind == "clause":
                history[-1]["content"] = progress_line(step.judged, step.total)
                yield _out(history)
            elif step.kind == "protections":
                history[-1]["content"] = (
                    "🐕 One more pass — checking the protections the law requires…")
                yield _out(history)
            elif step.kind == "done" and step.result.refused:
                # `step.kind == "done"` is named rather than left to an `else`. It used
                # to be one, and when the cap notice moved off `split` that step fell
                # through to here and dereferenced a `result` that is None on every
                # step but the last. A caller with nothing to say about a step kind
                # should ignore it, not crash on the way to the result.
                #
                # Not cached, and no panel pinned. The cache serves finished
                # reports and a hit is rendered as one, so keeping refusals out of
                # it costs one cheap classification call and keeps every other
                # path uniform. Leaving the context on law-only matters more:
                # telling ask mode "you have the scan report of X" when no clause
                # was judged would invent a report for it to reason from.
                yield _out(history, box=gr.update(interactive=True),
                           report="", state="", context=LAW_ONLY_CONTEXT, source="",
                           stop=gr.update(visible=False),
                           col=gr.update(visible=False),
                           actions=gr.update(visible=False))
            elif step.kind == "done":
                cache_put(digest, step.result)
                history[-1]["content"] = scan_summary(step.result)
                yield from finished_scan(step.result, name, key, history,
                                         context_base, question)
    except NoTextExtracted:
        history[-1]["content"] = NOTHING_EXTRACTED
        yield _out(history, box=gr.update(interactive=True),
                   report="", state="", context=LAW_ONLY_CONTEXT, source="",
                   stop=gr.update(visible=False), col=gr.update(visible=False),
                   actions=gr.update(visible=False))
    except DocumentTooLarge as oversized:
        history[-1]["content"] = TOO_LARGE.format(
            pages=in_pages(oversized.chars), limit=in_pages(oversized.limit))
        yield _out(history, box=gr.update(interactive=True),
                   report="", state="", context=LAW_ONLY_CONTEXT, source="",
                   stop=gr.update(visible=False), col=gr.update(visible=False),
                   actions=gr.update(visible=False))


def missing_protections(result: ScanResult) -> int:
    return sum(1 for p in result.protections if p["status"] == "missing")


def scan_summary(result: ScanResult) -> str:
    counts = count_verdicts(result.findings)
    coverage = (f" — across clauses 1–{result.clauses_judged} of {result.clauses_total}"
                if result.partial else "")
    # Same order as the report's own summary line and its sections: everything
    # actionable first, "clear" last. Three orderings of the same four counts is what
    # this used to be.
    return (
        f"🐕 Sniff complete{coverage}: 🚩 {counts['red']} red · "
        f"⚠️ {counts['yellow']} caution · "
        f"🔍 {missing_protections(result)} missing protections · "
        f"✅ {counts['green']} clear. "
        "Full report on the right — ask me about any clause."
    )


def finished_scan(result: ScanResult, name, key, history, context_base, question):
    """Pin the report and settle the panel — the caller has already said its piece
    in chat. Shared by the fresh and the cached path, which had drifted to calling
    `render_report` with different arguments for the same report."""
    args = (result.findings, name, DEMO_STATE, result.protections,
            result.gate_flagged, result.clauses_total)
    report = render_report(*args, jurisdiction=result.jurisdiction)
    # The panel gets HTML; `state` and the download keep the markdown, because the
    # chat reads the report as context and the download serves it as a .md file.
    panel = render_report_html(*args, jurisdiction=result.jurisdiction, markdown=report)
    yield _out(history, box=gr.update(interactive=True),
               report=panel, state=report,
               context=report_context(name), source=key,
               stop=gr.update(visible=False), col=gr.update(visible=True),
               download=gr.update(value=report_file(report, name)),
               actions=gr.update(visible=True))
    if question:
        yield from answer_flow(question, history, report, context_base)


def respond(message, history, report, scanned):
    """Guard around the real handler: an uncaught exception inside a generator
    event dies silently — the traceback goes to the server log and the user
    sees nothing happen at all (how a missing PDF dependency shipped). Turn any
    failure into a hound apology and restore the pre-turn panel state."""
    history = list(history)
    try:
        yield from _respond(message, history, report, scanned)
    except Exception:
        traceback.print_exc()
        history.append({"role": "assistant", "content": HOUND_TRIPPED})
        name = SAMPLE_LEASE.name if scanned == "sample" else Path(scanned).name
        yield _out(history, box=gr.update(interactive=True),
                   report=gr.skip(), state=report,
                   context=report_context(name) if report else LAW_ONLY_CONTEXT,
                   source=scanned, stop=gr.update(visible=False),
                   col=gr.update(visible=bool(report)),
                   actions=gr.update(visible=bool(report)))


def _respond(message, history, report, scanned):
    text = (message.get("text") or "").strip()
    files = message.get("files") or []
    if not text and not files:
        yield _out(box=gr.update(value=None))
        return
    context_base = list(history)  # snapshot before this turn's messages
    if files:
        path = Path(files[0])
        if path.name == SAMPLE_LEASE.name:
            # The sample-lease example: scan the repo file itself and cache as "sample".
            path, key = SAMPLE_LEASE, "sample"
        else:
            key = str(path)
        user_content = f"📎 `{path.name}`" + (f"\n\n{text}" if text else "")
        history.append({"role": "user", "content": user_content})
        yield _out(history, box=gr.update(value=None))
        # The canned example text is an instruction the scan itself fulfills —
        # don't answer it again as a follow-up question afterwards.
        question = "" if text == SCAN_EXAMPLE["text"] else text
        anyway = SCAN_ANYWAY_PHRASE in text.lower()
        # It was the override, not a question — answering "scan anyway" as a legal
        # question afterwards would be nonsense.
        if anyway:
            question = ""
        yield from scan_flow(path, key, history, report, scanned, context_base,
                             question=question, scan_anyway=anyway)
    else:
        history.append({"role": "user", "content": text})
        yield _out(history, box=gr.update(value=None))
        yield from answer_flow(text, history, report, context_base)


def on_stop(history):
    history = list(history)
    if history and history[-1]["role"] == "assistant":
        history[-1]["content"] = CALLED_OFF
    # The report was already invalidated at scan start, so the panel column
    # disappears again rather than showing a stale "scanning…" line.
    return (history, gr.update(interactive=True), "", gr.update(visible=False),
            gr.update(visible=False), gr.update(visible=False))


def on_trash():
    """Discard the pinned report: back to a law-only, solo-chat page.

    Silent, matching the chatbot's built-in clear button — the column
    collapsing and the context line reverting are feedback enough. (A chat
    message would merge into the previous assistant bubble and pollute the
    answering context; a toast would be this app's only toast.)
    """
    # TRASH_JS is sliding both columns to their solo positions right now; wait
    # it out so the DOM removal lands after the columns have stopped moving.
    time.sleep(0.5)
    return ("", "", LAW_ONLY_CONTEXT, "", gr.update(visible=False),
            gr.update(visible=False))


# Copy is client-side only — no server round-trip. Feedback: the copy icon
# itself becomes a checkmark in place for a moment (swapping the img src to a
# data URI; a check.svg on disk wouldn't be on Gradio's allowed-files list).
# Selected by the button's own id, not by its place in the row: this read
# `#report-actions button img` — the first button — and the checkmark moved to the
# delete icon the moment the row was reordered.
# The js handler must return a list (Gradio maps it to outputs).
CHECK_ICON = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" '
    'stroke="#6b7280" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
    '<polyline points="20 6 9 17 4 12"/></svg>'
)
# Reads the markdown out of the hidden field report_html.py leaves in the panel,
# not the panel's own value: that value is now HTML, and copying markup is not what
# this button promises. A gr.State would be the obvious home for the markdown, but a
# js-only handler runs entirely client-side and gr.State values only exist on the
# server — the same constraint that used to point this at the Markdown component.
COPY_JS = f"""
() => {{
    const field = document.querySelector('.report-panel .lh-md');
    navigator.clipboard.writeText(field ? field.value : '');
    const img = document.querySelector('#copy-report img');
    if (img) {{
        if (!img.dataset.copyIcon) img.dataset.copyIcon = img.src;
        img.src = 'data:image/svg+xml;utf8,' + encodeURIComponent({CHECK_ICON!r});
        setTimeout(() => {{ img.src = img.dataset.copyIcon; }}, 1200);
    }}
    return [];
}}
"""

# Examples send on click — one click, one message, like example chips in chat
# apps; they're complete questions, there's nothing to edit first. Gradio's
# Examples component only fills the box (run_on_click can't pass the state
# inputs respond needs), so a page-level listener waits for the fill to land
# and clicks send. The scan example also attaches a file — wait for its chip,
# or the submit would race the attachment and send text alone.
EXAMPLES_JS = """
() => {
    // Put the cursor in the message box on load, so a visitor can start typing
    // without clicking first. Deliberately not Gradio's autofocus=True: that
    // scrolls the focused input into view, measured at 713px down, which pushes
    // the wordmark and the one-click scan example off the top of the page.
    // preventScroll buys the focus without the jump.
    let focusTries = 0;
    const focusBox = setInterval(() => {
        const input = document.querySelector('.chat-col .multimodal-textbox textarea');
        if (input) {
            input.focus({preventScroll: true});
            clearInterval(focusBox);
        } else if (++focusTries > 40) {
            clearInterval(focusBox);
        }
    }, 50);

    document.addEventListener('click', (event) => {
        const chip = event.target.closest('#example-scan button, #example-prompts button');
        if (!chip) return;
        const needsFile = !!chip.closest('#example-scan');
        let tries = 0;
        const timer = setInterval(() => {
            const box = document.querySelector('.chat-col .multimodal-textbox');
            const filled = box.querySelector('textarea').value.trim()
                && (!needsFile || box.querySelector('.thumbnail-item'));
            if (filled) {
                clearInterval(timer);
                box.querySelector('.submit-button').click();
            } else if (++tries > 60) {
                clearInterval(timer);
            }
        }, 50);
    });
}
"""

# Starts the two-columns-to-one slide immediately on click; on_trash sleeps
# past the transition before removing the report column from the DOM. The
# class comes off on a timer (the column is long gone by then) so a future
# report isn't born collapsed.
TRASH_JS = """
() => {
    const row = document.querySelector('.main-row');
    if (row) {
        row.classList.add('closing');
        setTimeout(() => row.classList.remove('closing'), 700);
    }
    return [];
}
"""


# Gradio 6 moved theme/css/js off the Blocks constructor. Theme and css belong to
# whoever serves the Blocks, and there are two of those — `launch()` here and
# `mount_gradio_app()` in api.py — so they live in one dict rather than being
# spelled out twice and drifting.
#
# `js` is deliberately NOT in here. Passing it to launch() is accepted and then
# silently never runs: the script is absent from the page and activeElement stays
# on <body>, which killed both the autofocus and the click handler that makes the
# example chips submit. It has to be a load event instead (see demo.load below).
UI_STYLE = {
    "theme": gr.themes.Soft(
        primary_hue="teal",
        neutral_hue="slate",
        font=[gr.themes.GoogleFont("Inter"), "ui-sans-serif", "system-ui", "sans-serif"],
    ),
    "css": CSS,
}

# Tab title is the wordmark alone. A tab is ~20 characters of usable space beside the
# favicon, and the 🐕 already says which app this is; the descriptive half lives in
# SOCIAL_TITLE below, where a link preview has room for it.
with gr.Blocks(title="LeaseHound") as demo:
    gr.HTML(HERO)
    report_state = gr.State("")
    scanned_source = gr.State("")  # what the current report is for: a file path or "sample"

    with gr.Row(elem_classes="main-row"):
        with gr.Column(scale=1, elem_classes="chat-col"):
            context_line = gr.Markdown(LAW_ONLY_CONTEXT, elem_classes="step-sub")
            # Gradio 6 dropped `type=`: the messages format this app already uses
            # is the only one now, so the argument became a no-op and then an error.
            # Gradio's default toolbar is ["share", "copy_all"], and its "share"
            # posts to Hugging Face Spaces Discussions — a no-op anywhere else, so
            # on Cloud Run it is a button that cannot do anything. Naming the list
            # drops it and keeps the two that work.
            chatbot = gr.Chatbot(height=440, show_label=False,
                                 buttons=["copy", "copy_all"])
            message_box = gr.MultimodalTextbox(
                placeholder="Attach a lease, or ask about renting in Washington…",
                show_label=False,
                file_types=[".pdf", ".md", ".txt"],
                file_count="single",
                # Cursor lands here on load: asking is the zero-friction entry
                # point, and the scan button is one click away either way.
            )
            gr.Examples(
                examples=[SCAN_EXAMPLE],
                example_labels=[SCAN_EXAMPLE_LABEL],
                inputs=message_box,
                label="Scan a lease",
                elem_id="example-scan",
            )
            gr.Examples(
                examples=QUESTION_EXAMPLES,
                inputs=message_box,
                label="Ask a question",
                elem_id="example-prompts",
            )
        with gr.Column(scale=1, visible=False, elem_classes="report-col") as report_col:
            stop_button = gr.Button(
                "✋ Call off the hound", variant="stop", size="sm", visible=False
            )
            # One row pinned at the panel's top-right corner (see the CSS), so
            # all three actions share the same position and appear together,
            # only once a finished report is up.
            # Discard, copy, download — matching the chat toolbar beside it, which
            # reads Clear then Copy. That order is Gradio's: `buttons` accepts only
            # "share"/"copy"/"copy_all" or custom buttons, and the Clear it renders
            # ahead of them is not in that list and cannot be moved. Two toolbars a
            # few hundred pixels apart disagreeing about where "delete" lives is the
            # kind of thing a visitor notices, so the one we control follows the one
            # we do not.
            with gr.Row(visible=False, elem_id="report-actions") as report_actions:
                trash_button = gr.Button("", icon=str(ICONS / "trash.svg"), size="sm")
                # elem_id because COPY_JS has to find THIS button's icon to swap it
                # for a checkmark. It used to select the first button in the row,
                # which was this one until the row was reordered to match Gradio's
                # chat toolbar — after which clicking copy put the checkmark on the
                # delete button. Position is not identity.
                copy_button = gr.Button("", icon=str(ICONS / "copy.svg"), size="sm",
                                        elem_id="copy-report")
                download_button = gr.DownloadButton("", icon=str(ICONS / "download.svg"), size="sm")
            # gr.HTML, not gr.Markdown: the panel renders report_html.py's markup,
            # and Markdown would put it through DOMPurify with a config this repo
            # cannot read. Escaping every interpolated value in one module is a
            # boundary that can be tested; guessing an allow-list is not.
            report_output = gr.HTML("", elem_classes="report-panel")

    outs = [chatbot, message_box, report_output, report_state,
            context_line, scanned_source, stop_button, report_col, download_button,
            report_actions]
    submit_event = message_box.submit(
        respond, inputs=[message_box, chatbot, report_state, scanned_source], outputs=outs,
        show_progress="hidden",
    )
    stop_button.click(
        on_stop, inputs=[chatbot],
        outputs=[chatbot, message_box, report_output, report_col, stop_button,
                 report_actions],
        cancels=[submit_event],
    )
    trash_button.click(
        on_trash,
        outputs=[report_output, report_state, context_line,
                 scanned_source, report_col, report_actions],
        show_progress="hidden",
        js=TRASH_JS,
    )
    # No inputs: COPY_JS reads the markdown straight out of the DOM. See its comment.
    copy_button.click(None, js=COPY_JS)
    # Client-side setup: focus the input, and make the example chips submit. A load
    # event is the only place this runs under Gradio 6 — see UI_STYLE above.
    demo.load(None, js=EXAMPLES_JS)

# Public-hosting guardrails: a bounded waiting room instead of an unbounded
# queue, and a few concurrent turns so one long scan doesn't serialize everyone.
# Named rather than inlined because scripts/measure_concurrency.py does the
# admission arithmetic from them — it used to restate the two numbers in its own
# source, which would have gone stale the moment either changed here.
QUEUE_MAX_SIZE = 16
QUEUE_CONCURRENCY = 4
demo.queue(max_size=QUEUE_MAX_SIZE, default_concurrency_limit=QUEUE_CONCURRENCY)

# The outer half of the size bound, and the only half that acts on BYTES.
#
# scan.MAX_DOCUMENT_CHARS is the one that matters for spend, but it can only fire
# after read_document has parsed the upload — and parsing is itself the memory event
# worth avoiding: pypdf holds the whole file, and this deployment is one instance
# whose measured peak across four concurrent scans is ~300 MB. Gradio's default here
# is None, i.e. unlimited, so without this line a large enough upload is an OOM before
# any of the reasoning in scan.py gets a turn.
#
# Looser than the character limit on purpose: these bound different things. A PDF that
# is mostly scanned images carries few characters per megabyte, and that document has
# earned the "no text layer" answer it already gets rather than a size error.
#
# But not much looser, and the deployment is why. The service runs on 1 GiB with
# `--max-instances 1` and Cloud Run's own `containerConcurrency` at 80 — which is not
# the 4 that Gradio's queue enforces, because the queue governs event handlers and an
# upload arrives before any handler runs. Cloud Run also has no disk: bytes written to
# the filesystem are charged to the same 1 GiB. So the stress case is concurrent
# uploads, not concurrent scans, and this keeps even an absurd 80 of them under the
# limit alongside the ~300 MB the app already occupies.
#
# Gradio wants a string or an int; the int from upload.py is the one source of truth,
# and api.py reads the same constant so the two surfaces cannot drift apart.
MAX_UPLOAD_SIZE = MAX_UPLOAD_BYTES

# Gradio hard-codes its own Open Graph tags into the page it serves, so the link
# preview on LinkedIn, Slack or a recruiter's inbox reads "Gradio — Click to try out
# the app!" under someone else's Twitter handle, and og:url ships as the literal
# unsubstituted string "{url}". The favicon was the visible half of this; the share
# card is the half that reaches people who never click. Rewritten on the way out
# because the tags are baked into Gradio's template, not configurable.
DEMO_URL = "https://leasehound-671004460975.us-west1.run.app"
# A purpose-built 1200x630 card, not the README still: every platform crops share
# images to about 1.91:1, and the screenshot is 1.42:1, so a quarter of its height
# was cut — and at card size its UI text was unreadable anyway. Regenerate with
# scripts/make_og.py, which reads the two strings below so the card cannot drift
# from these tags. Served from the public repo so a scraper can reach it.
SHARE_CARD = "docs/og.png"
SOCIAL_TITLE = "LeaseHound — lease red-flag scanner"
SOCIAL_DESCRIPTION = ("Scan a Washington lease for clauses that are void under "
                      "RCW 59.18 — every verdict cites the statute.")
# Card only, never in the meta description. The description is read by whoever gets
# the link and should say what the thing does; the card is read by people scanning
# for what it is built out of. Both audiences are real and want different sentences.
SOCIAL_STACK = "Two-layer RAG over Washington tenant law"
# The card shows one real finding. The clause text is read out of the sample lease
# rather than retyped — an invented quotation on a card about citing sources would be
# the one mistake this project cannot afford. The section is the verdict a real scan
# of that lease returns; it is the pairing recorded in docs/screenshot.png.
CARD_CLAUSE_HEADING = "3. LATE CHARGES."
CARD_CITATION = "RCW 59.18.170 — no late fee before the fifth day"
# The verdict counts the report shows for that lease. Not derived, and the reason
# is worth recording: evaluation/scan_results.json has `flagged_yellow`, but that
# field means "planted violations that came back yellow" — a different quantity
# from "cautions in the report", which lands in `cautions` (eval_scan.py:123) and
# is written out as `unplanted_yellows`. That field was added after the stored
# artifact was generated, so the artifact cannot supply this count today. The
# clear count is not arithmetic either: 7+1+7 exceeds the numbered lines in the
# lease, because the scanner's clause splitting is not a regex over "N.".
# These are what the live app returns, the same run recorded in docs/screenshot.png.
# Re-derive from `unplanted_yellows` the next time the scan eval is re-run.
CARD_VERDICTS = "7 red flags | 1 caution | 2 missing protections | 7 clear"
# Matched by attribute rather than by exact string: Gradio emits these twice, in two
# blocks, and wraps some of them across lines, so a literal replacement caught the
# titles and left og:image pointing at Gradio's own banner. An empty value here means
# drop the tag — shipping someone else's URL is worse than shipping none.
SOCIAL_CONTENT = {
    "og:title": SOCIAL_TITLE,
    "twitter:title": SOCIAL_TITLE,
    "og:description": SOCIAL_DESCRIPTION,
    "twitter:description": SOCIAL_DESCRIPTION,
    "og:url": DEMO_URL,
    "og:image": f"https://raw.githubusercontent.com/tywangq/leasehound/main/{SHARE_CARD}",
    "twitter:image": f"https://raw.githubusercontent.com/tywangq/leasehound/main/{SHARE_CARD}",
    "twitter:creator": "",
    "twitter:site": "",
}
META_TAG_RE = re.compile(r'<meta\s[^>]*?(property|name)="([\w:]+)"[^>]*?/>', re.S)


def rebrand_meta_tag(match: re.Match) -> str:
    attribute, key = match.group(1), match.group(2)
    if key not in SOCIAL_CONTENT:
        return match.group(0)
    value = SOCIAL_CONTENT[key]
    return f'<meta {attribute}="{key}" content="{value}" />' if value else ""


async def rebrand_social_preview(request, call_next):
    """Swap Gradio's share-card metadata for this app's, on HTML responses only."""
    response = await call_next(request)
    if not response.headers.get("content-type", "").startswith("text/html"):
        return response
    body = b"".join([chunk async for chunk in response.body_iterator])
    text = META_TAG_RE.sub(rebrand_meta_tag, body.decode("utf-8", "replace"))
    # Declared rather than left to the browser's default /favicon.ico probe, so the
    # tab icon does not depend on a fallback. PNG, not SVG: this shipped as an SVG
    # holding the emoji as `<text>`, served a correct 200 image/svg+xml, and showed
    # nothing — Safari does not support SVG favicons at all, and a text glyph needs
    # an emoji font resolved inside the favicon's rendering context. See
    # scripts/render_favicon.py, which draws the real glyph in a real browser.
    text = text.replace("<head>", '<head>\n\t\t<link rel="icon" type="image/png" '
                                  'href="/favicon.ico" />', 1)
    headers = {k: v for k, v in response.headers.items() if k.lower() != "content-length"}
    return Response(content=text, status_code=response.status_code,
                    headers=headers, media_type="text/html")


def serve() -> None:
    """One process, two surfaces: the UI at / and the HTTP API at /v1.

    Mounted rather than launched, so `python -m leasehound.app` stays the single
    serving command — the container's CMD, the README, and .claude/launch.json all
    keep working, and there is no second entry point to remember which of the two
    a given environment runs. The env vars are Gradio's own names because that is
    what the Dockerfile already sets.
    """
    import uvicorn

    from leasehound.api import api

    server = gr.mount_gradio_app(api, demo, path="/",
                                 favicon_path=str(ICONS / "favicon.png"),
                                 max_file_size=MAX_UPLOAD_SIZE, **UI_STYLE)
    server.middleware("http")(rebrand_social_preview)
    uvicorn.run(
        server,
        host=os.environ.get("GRADIO_SERVER_NAME", "127.0.0.1"),
        port=int(os.environ.get("GRADIO_SERVER_PORT", "7860")),
    )


if __name__ == "__main__":
    serve()
